### ISSUE TITLE
Bed numbers should be editable

### ISSUE THREAD

**Issue by aeon-lakes** [neherlab/covid19_scenarios#10]
Please allow us to edit hospital beds and ICU beds. 

I'm trying to get ventilated beds expanded in my institution in anticipation of an onslaught. Switzerland is doing well for ICM beds in comparison to my home country, we have far fewer. Being able to show our own nation's Total Hospital Beds and ICU beds overwhelmed under different scenarios would be useful for those of us who have to persuade the people with the dollars. 

Thank you for your hard work.

**Comment by pinanunes** [comment]
Great work,

I would second this request (actually the big question now). Adding total beds or beds per 100.000 and add a transition rate between C and D with ICU and C and D' for critical cases above number of available beds. 
For default values per country this sources can be used:
https://link.springer.com/article/10.1007/s00134-012-2627-8
https://gateway.euro.who.int/en/indicators/hfa_479-5061-number-of-acute-care-hospital-beds/
(Europe only)

Thank you! Great work

**Comment by rneher** [comment]
thanks for the reference. we'll try to make these numbers available through the app asap

**Comment by aeon-lakes** [comment]
'ICM/ICU beds' overstates capacity. There are generally less ventilated beds than physical beds in an Intensive Care Unit. Given the numbers of critically ill with SARS/ARDS COVID-19 produces and their subsequent long ICU stay, the important number is really _ventilated beds_ rather than ICM/ICU beds. Once ventilator capacity is occupied, it is the critically ill in excess of that number (that need ventilation but can't be accommodated) who will become inevitable mortalities. 

2010 numbers for Australia and New Zealand are here: https://journals.sagepub.com/doi/pdf/10.1177/0310057X1003800124

Given the overstatement of ICM/ICU capacity provided by official numbers in this context, the ability to directly enter known ventilated bed capacity for the simulated area, rather than pull down from an ICU/ICM number list is more helpful. Perhaps even more so if it could be changed to reflect increasing capacity during the selected term of the simulation (that's only a 'nice to have' though).

**Comment by pinanunes** [comment]
I must agree with @aeon-lakes. Maybe is better to have it as a value or even as a time-dependent value as used on mitigation.

**Comment by aeon-lakes** [comment]
This paper: https://www.nejm.org/doi/full/10.1056/NEJMoa2002032
Suggests 2.3% of treated COVID-19 patients or around half of ICU patients were invasively ventilated. It doesn't state whether ventilation was indicated for more, but that's a ballpark figure to calculate ventilator demand? Cases above that calculated number would become deaths.

**Comment by rneher** [comment]
We have added fields now. Thanks for the pointers. We'll clean up the input data and hopefully have a table that can be readily extended. Making the fatality rate a function of load is on the list!
