### ISSUE TITLE
Containment graph looses its values

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#102]
In https://github.com/neherlab/covid19_scenarios/pull/99 @dannysepler reported the following with relation to Containment (mitigation) graph component and modifying the number of points:

> If you bring the number to 1 and then back to 10, the y values of the graph are lost seemingly until you refresh. I don't really know why this is.

More investigation and reproduction steps are needed.

**Comment by dannysepler** [comment]
for more details, here's a pic of before:

<img width="645" alt="Screen Shot 2020-03-21 at 11 35 30 PM" src="https://user-images.githubusercontent.com/3710083/77241722-d9374580-6bcc-11ea-91a2-e70bc1dd001a.png">

and after: 

<img width="632" alt="Screen Shot 2020-03-21 at 11 35 40 PM" src="https://user-images.githubusercontent.com/3710083/77241723-ddfbf980-6bcc-11ea-8615-b2c068546b93.png">

**Comment by ivan-aksamentov** [comment]
@dannysepler 

Ah, yes, I think it might be due to interpolation. My hypothesis is that if you change number of points, the algorithm tries to fit the existing curve into the new number of points.

If number of points is reduced, then there is information loss. The loss is small with large number of points, but  as it approaches 1 point more data is lost. And with 1 point it degrades to the value of that point.

One point is an extreme case that does not make much sense in terms of reality, so we may just limit minimum to 5 or 10 for example.

Another possible workaround now (workaround of workaround :) ) might be to retain old points as much as possible, but exclude them from calculations.

I think interpolation might be eliminated when https://github.com/neherlab/covid19_scenarios/issues/14 will get implemented.

@nnoll @rneher Could you please take a look?

**Comment by rneher** [comment]
Yes, this is due to the interpolation. I think maintaining an internal copy of additional points while only displaying a few will result in even more confusing and unexpected results. Interpolating the graph with less than 5 values doesn't make much sense. issue #14 or related ideas should alleviate this. For the time being, we can impose a minimum on the number of points.

**Comment by ivan-aksamentov** [comment]
Closing because containment graph is now removed
