### ISSUE TITLE
Add landing page

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#107]
Currently the application just dumps user right into the simulator. No explanations, no context, just a form and a "Run" button.

We would like to add a Landing page:
 - [x] spacey, lots of color, curvy SVG lines and a large SVG image of coronavirus (if available, let's discuss options/licensing/costs)
 - [x] a large button in the middle to launch a simulator (e.g. "Simulate")
 - [ ] basic intro in a few words: what, why, who. Not too much science. Not boring.
 - [ ] refer to science details with a link
 - [x] a checkbox to skip the landing page after the first visit (saved in the local storage)

**Comment by tryggvigy** [comment]
I'm no designer but is this close to what you have in mind?

| Mobile | Desktop |
| -| -|
| ![Google Pixel 2 - 2](https://user-images.githubusercontent.com/2373958/77256180-77c2b580-6c64-11ea-8882-ef11e40077fa.png) | ![MacBook Pro - 1](https://user-images.githubusercontent.com/2373958/77256177-76918880-6c64-11ea-9529-507fd7574162.png)

There is plenty of space to move things around and add more content

**Comment by ivan-aksamentov** [comment]
@tryggvigy Holy Molly, this is gorgeous!
I will merge the same second you submit a PA :heart_eyes:

**Comment by tryggvigy** [comment]
Great! I'll start working on a PR as soon as I can.

---------

> basic intro in a few words: what, why, who. Not too much science. Not boring.
> refer to science details with a link

Any thoughts already on exact text we want in these and other sections of the landing page?

**Comment by ivan-aksamentov** [comment]
@tryggvigy You can play with what the Overview section in the Readme has
https://github.com/neherlab/covid19_scenarios/blob/master/README.md#overview
It will probably need to be slightly less scientific and somewhat shorter. Feel free to rephrase and to adjust the length to mobile use-case.
We can link to About page and FAQ, but I'm afraid we may lose users there, as they will not know where is simulator now. Links and navigation have to be planned carefully too.

**Comment by tryggvigy** [comment]
I got some progress on this today. https://github.com/neherlab/covid19_scenarios/pull/163

@ivan-aksamentov do you think we should have the landing page be a separate url from the simulator? It would require us to change the routing a bit. What I mean is something like:

The landing page would be https://neherlab.org/covid19/
and the simulator would live under https://neherlab.org/covid19/simulate.

Then we could do a redirect from `/` to `/simulate` in react router if the user has chosen to now see the homepage again (based on the local storage flag).

**Comment by ivan-aksamentov** [comment]
@tryggvigy 
What do you think would be the best user experience?

Can we pretend that both are in the `/` and just conditionally render? Not a best practice typically, right? And bad for SEO probably.

Or can we redirect to `/start` (landing) on first visit and keep simulator on `/`.

I want the URL to be short and intuitive, becaue we already have a mess of a domain name.

We also have now links that persist parameters, like:
`https://neherlab.org/covid19/<a_bunch_of_serialized_json>`
(not intuitive at all)
that allows users to save, restore and share the params.

P.S. We will be moving to new domains soon, when the new UX and autorelease tool will be ready:
https://staging.covid19-scenarios.org (autodeploy from `master`)
https://covid19-scenarios.org (autodeploy from `release`)
So ignore any concerns regarding serving from subdirectory, if any appear.

P.P.S. Note that we are using `connected-react-router` (because we are fancy :) )
https://github.com/supasate/connected-react-router/blob/master/FAQ.md#how-to-navigate-with-redux-action

**Comment by ivan-aksamentov** [comment]
Some more ideas spontaneously emerged here
https://github.com/neherlab/covid19_scenarios/pull/163#pullrequestreview-383260554

So I'll reopen

**Comment by ivan-aksamentov** [comment]
Resolved  in #163
