### ISSUE TITLE
Export to PDF, print layout and printing

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#110]
Additionally to the export to JSON and CSV, and so long awaited import features, we may also add export of parameters and results to PDF or a similar format (or multiple).

The use case: this would serve as a report generator for "busy executives". For example, scientists or medics would first tweak the simulator and then generate a PDF that is ready to be presented to their superiors, local politicians, medical services etc.
Also the same document might as well be printed right in the app. 

I think bootstrap have a way to setup print layouts separately. Alternatively we may just generate a page in background on the fly and then write it using HTML5 file API.

**Comment by guandiyiyi** [comment]
@ivan-aksamentov, did we try solution of https://www.npmjs.com/package/react-pdf ? If not, I can give it a try and circle back if this solution work.

**Comment by ceporche** [comment]
Hi @ivan-aksamentov I'd like to commit to this issue.

**Comment by ivan-aksamentov** [comment]
We need to accelerate this as it is a priority feature now

**Comment by noleti** [comment]
maybe completely unrealistic, but: automated text generation with great layout is of course possible with LaTex, with the main caveat that the .tex compilation cannot be done in the client-side app. Compilation on the server would require new code and is not without security issues (we would need good validation etc). Maybe someone knows an API that will compile for us? Or (for academic end users) we provide a .zip with .tex+images (and/or suggest overleaf to compile)>

**Comment by rneher** [comment]
I like the tex idea and overleaf might be a solution (we use it a lot). But we now have a pretty good print-solution which will be good enough for the next milestone.
