### ISSUE TITLE
Export: permission dialog to download more than one file

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#111]
The "Export" button implements export to files.

Because there is more than one file per one button click, browser triggers a permission dialog for allowing our app to download more than one file. If blocked, all future downloads are blocked for the domain, until explicitly re-allowed in privacy settings.

What would be the best way to proceed? For example:
 - leave as is (the permission dialog may scare some users)
 - add multiple buttons (one click per file)
 - pack into a zip (requires the user to unzip)
 - don't download, but just show a large popup with the contents of all files so that user can copy-paste

See also:
https://github.com/neherlab/covid19_scenarios/issues/11

Screenshots:

<a href="https://user-images.githubusercontent.com/9403403/77240540-5c659500-6be7-11ea-98c0-4a7652aaae5e.png">
<img width="45%" src="https://user-images.githubusercontent.com/9403403/77240540-5c659500-6be7-11ea-98c0-4a7652aaae5e.png"/>
</>

<a href="https://user-images.githubusercontent.com/9403403/77240563-be25ff00-6be7-11ea-9ffe-d1319a5b0a0f.png">
<img width="45%" src="https://user-images.githubusercontent.com/9403403/77240563-be25ff00-6be7-11ea-9ffe-d1319a5b0a0f.png"/>
</a>

**Comment by rcbevans** [comment]
I agree that a dialog asking about downloading "multiple" files, especially on first click, could be scary to some.  They may suspect that the file they wanted is downloaded, but the site is trying to sneakily add additional files onto their machine.

Worse, Chrome has a browser setting with auto-blocks any site from downloading multiple files, without even displaying a prompt to the user, in which case they wouldn't even realize that the download was incomplete.  The way that most sites with bulk download work (e.g. Google Drive, OneDrive) is to list individual files, with an option to "download all" as well, in which case, a zip containing all files is downloaded.

I think a good UX would be to show a pop up modal when the user clicks export listing the various files available which they can click individually to download that file, with a download all button at the bottom of the modal which will trigger a zip operation, followed by download of the archive.

**Comment by ivan-aksamentov** [comment]
@rcbevans I was also thinking about a separate window.

We might implement a unified user experience for everything related to persistence: 
 - [x] export to params,json + results.csv (.zip, list of files, copy-paste text)
 - [ ] import from params,json and/or results.csv 
 - [ ] saving to local storage (possibly to server later on)
 - [x] sharing via URL (analog of params.json)
 - [ ] sharing on with social media buttons

**Comment by rcbevans** [comment]
Browsers also show warnings in relation to pop-ups, in the same way as with downloading files, and pop-ups themselves can cause usability issues; frustration/confusion if a window is created and the user clicks elsewhere causing the pop-up to disappear behind the focused primary window.

**Comment by ivan-aksamentov** [comment]
@rcbevans browsers show warnings only for he actual popup windows, right? Like the new browser instances. I meant more like bootstrap popup modals, similar to yours in https://github.com/neherlab/covid19_scenarios/issues/25, but maybe a bit bigger.

**Comment by ivan-aksamentov** [comment]
Haha reread my message https://github.com/neherlab/covid19_scenarios/issues/111#issuecomment-602388260 and it says "separate window". No, of course we will not have popups from year 1999 :)

**Comment by rcbevans** [comment]
Ah, sorry.  Pop-up I always assume to be new browser windows; yes, browsers have warnings for those.  I initially meant modal dialog which is the dialog which renders over the rest of the page content, as in my other PR; no warnings for those.

**Comment by ivan-aksamentov** [comment]
@good. In fact, we already have something like this for import:

https://github.com/neherlab/covid19_scenarios/blob/6ddaba72706eb6f69b80a687c92dd7fd2253d104/src/components/Main/Compare/ComparisonModalWithButton.tsx

but it needs more love...

**Comment by rcbevans** [comment]
I'll pick this up now.

**Comment by rcbevans** [comment]
@ivan-aksamentov got a PR up for review adding the functionality as described.

![Screenshot of export scenario dialog](https://user-images.githubusercontent.com/2041260/77617724-1879d500-6ef2-11ea-9fd2-6eb3ba2f24e4.png)
