### ISSUE TITLE
Strong Mitigation Scenario Crashes Page

### ISSUE THREAD

**Issue by kapawlak** [neherlab/covid19_scenarios#12]
Instant crash. Running on Chrome Version 80.0.3987.132 (Official Build) (64-bit Windows)

![one](https://user-images.githubusercontent.com/29474019/76709850-50497700-66bf-11ea-82be-161eee2f573d.png)

![errrrr](https://user-images.githubusercontent.com/29474019/76709848-4fb0e080-66bf-11ea-909c-89dbc89bb80f.png)

**Comment by rneher** [comment]
thanks, Kelly! should be fixed now (might need hard reload) in commit adb6bbc4fe6d6e5b25eb225e8e98d0041c776fb2
