### ISSUE TITLE
Flexible time range for population presets

### ISSUE THREAD

**Issue by rneher** [neherlab/covid19_scenarios#120]
# 🙋 Feature Request
The top left panel contains population parameters and the simulation time range. The latter partly belongs to the population (the start of the outbreak) and is partly depends on the question the user is asking.  tMin in particular should be tied to the initial case count. 

## 🤔 Expected Behavior
The initial condition should be flexible both with regard to case count and time. Wuhan for example needs 100 cases in Dec 19. 

## 😯 Current Behavior
Hard coded to March 1st

## 💁 Possible Solution
Split the `populationData.tsv` into a set of fixed population parameters (size, hospital beds, ageDistribution key) and an `inititalCondition.json`.  

We could either parse `initialCondition` could be parsed into the `src/assets/data/scenarios/population.json` or make 

https://github.com/neherlab/covid19_scenarios/blob/master/src/assets/data/scenarios/simulation.ts

population specific in analogy to 

https://github.com/neherlab/covid19_scenarios/blob/master/src/assets/data/scenarios/population.ts

We could tie population and simulation presets to the same default scenario key. This would require only few changes in the rest of the code base.

**Comment by nnoll** [comment]
An additional thought on this overhaul is that it would be nice to have the % confirmed cases also toggle-able by scenarios. This could be estimated from our case/death data just as tMin and the number of initial cases.
