### ISSUE TITLE
Improve desktop user experience

### ISSUE THREAD

**Issue by heuermh** [neherlab/covid19_scenarios#13]
Thank you for this useful resource!  Unfortunately it is rather difficult to work with in the web browser because of the rigid boxy layout.  Labels, values, and column headers are truncated and/or difficult to read.

Please consider a more flexible web layout; perhaps moving the Results box to the bottom might help.

**Comment by ivan-aksamentov** [comment]
Hi @heuermh ,
Yes, the user experience is currently suboptimal, especially on any screen that is smaller than a typical 1080p. Having only limited amount of resources, we primarily focused on the tool to be useful, but now we are definitely want to invest into making it prettier and to improve usability.

Currently we use `bootstrap` (more specifically, `reactstrap`) for the grid layout, so on smaller screens Results box eventually goes to the bottom.

The difficulty is to test all that on different displays. Also we have some small elements, like form inputs and large elements, like plots. And it is not obvious how to compose them better, while also preserve the grouping into scenarios.

Do you have difficulties on a particular device? Let me know the resolution and screen size or DPI.

Going further we may look into tweaking the layout, for example by:

 * adjusting the bootstrap's breakpoints (we use the Sass version, so overriding the default variables should be not too hard)
 * adjusting the column sizes for different screens (see `Col` components through the app's source code)
 * replacing bootstrap with something else
 * shortening the form labels and moving the information into the corresponding help boxes
 * adding ellipsis-truncation to form labels
 * warning the users ("optimized for desktop, 1080p and larger" or something like that)

See also:
 - [Bootstrap documentation](https://getbootstrap.com/docs/4.1/getting-started/introduction/)
 - [Reactstrap documentation](https://reactstrap.github.io/)

We appreciate any help with this.

![Peek 2020-03-16 23-11](https://user-images.githubusercontent.com/9403403/76850810-6c2c5480-6848-11ea-8143-5579886dd29c.gif)

**Comment by heuermh** [comment]
Thank you, @ivan-aksamentov, for the detailed response!  I will follow the work in #83 and contribute if I am able to.

**Comment by rneher** [comment]
The initial layout is largely replaced and we have many improvements. There is still stuff to do, but I am closing this in favor of more specific issues.
