### ISSUE TITLE
Scrolling position is remembered incorrectly after page reload

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#142]
# 🐛 Bug Report

I don't have the exact steps yet. It is especially noticeable on a narrow device. Also when dev tools are open wide and the viewport is narrower and can be scrolled.

## 🤔 Expected Behavior

Remembered scrolling position is reset after page reload, preferably.
Otherwise, maybe at least reset after I scroll to the top?
Lack of memory whatsoever would also be fine. We don't need fancy.

## 😯 Current Behavior

Scroll position is being retained needlessly and unexpectedly. Also wrongly (the position is not the same as)

After scrolling and then refreshing the page (F5, Ctrl+F5) the browser scrolls to some place, not necessarily where I scrolled previously. After scrolling to the top page and refreshing it is still scrolling somewhere.

## 💁 Possible Solution

Suspected offender PRs:
https://github.com/neherlab/covid19_scenarios/pull/84
https://github.com/neherlab/covid19_scenarios/pull/103

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System |
| NPM/Node/Yarn    |

**Comment by rneher** [comment]
this behavior goes away if the condition here

https://github.com/neherlab/covid19_scenarios/blob/master/src/components/Main/Main.tsx#L129

evaluates to false.

**Comment by ivan-aksamentov** [comment]
Fixed in #179
