### ISSUE TITLE
Prettify About, Team and upcoming FAQ pages

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#148]
We need to make these a bit prettier, because right now it's a pure horror.

Unleash your imagination! 👨‍🎨

Related:
https://github.com/neherlab/covid19_scenarios/issues/147

P.S. FAQ page can be found on branch `feat/faq`

**Comment by kimuraz** [comment]
Hi, can I work on this issue? * I'm not a designer*.  I've been working with frontend development for a while and saw some opportunities to adopt patterns that are commonly used on some other applications. If approved, I'd be glad to implement it.

Two points that concerns the whole application, would be:
1) Add a padding-top for all the containers with `20px`, making the spacing between the navbar and the content better.
2) Change a little bit the layout for the navbar, making your logo more visible and pushing the links to the right.
![image](https://user-images.githubusercontent.com/9062864/77799908-0fb20c00-7076-11ea-97c5-4298b132b6b9.png)

3) For the Team page, following the layout of the about page, something like:
![image](https://user-images.githubusercontent.com/9062864/77800613-7683f500-7077-11ea-941b-f012bee5a0f9.png)

4) For the FAQ page, just use an "Accordion" like [this](https://react-bootstrap.netlify.com/components/accordion/), that can be achievement on reactstrap as well. This can highlight the question and make it easier to the user to search for it, also focus on a single answer at the time.

What do you think?

**Comment by ivan-aksamentov** [comment]
@kimuraz , sure, go ahead!
Make sure you roughly align the style with https://github.com/neherlab/covid19_scenarios/pull/195

(preview: https://covid19-scenarios-kr9r4tzcm.now.sh/)

You may save some time and take the team snippet from 
https://github.com/neherlab/covid19_scenarios/blob/master/README.md#initial-development
feel free to use MDX for pages or just components as well.

You can also add "Contributors section" to the team page. We auto-generate this snippet:
https://github.com/neherlab/covid19_scenarios/blob/master/src/assets/text/contributors-generated.md
with 
https://github.com/all-contributors/all-contributors

Important: all the main content in About and FAQ pages should be  in MD or MDX, so that Richard could update it more easily, without struggling with JSX :) Page layout can be in JSX.

And feel free to add yourself there to test how it works in the end :)
See their CLI documentation for how to do that.

**Comment by kimuraz** [comment]
On it @ivan-aksamentov, will post some updates here when need. Thanks for the guidance.

**Comment by ivan-aksamentov** [comment]
Mostly resolved by #263
