### ISSUE TITLE
Fix plot rendering on mobile

### ISSUE THREAD

**Issue by rneher** [neherlab/covid19_scenarios#15]
The results plot on mobile is squished in portrait mode.

**Comment by ivan-aksamentov** [comment]
Potential solutions include:

 * having a button to open plots in a separate "screen"  (e.g. modal popup) which render the plot in landscape orientation on mobile
 * force mobile users with screen width below  a given threshold to landscape mode at all times (bad)

**Comment by ivan-aksamentov** [comment]
The plot looks a bit better, or at least usable. But there is still lots of work on mobile.
I will close this and move the efforts to the more general issue:
https://github.com/neherlab/covid19_scenarios/issues/71
