### ISSUE TITLE
Essential routes shouldn't be chunked separate to the main bundle

### ISSUE THREAD

**Issue by rcbevans** [neherlab/covid19_scenarios#150]
Currently, each page (home, about, notfound, team) is rendered via the `Loadable` component which uses webpack magic comments and promise based resolution to achieve chunking, seeking to make the initial page load smaller.

It doesn't make much sense to have main page content loading outside of the initial bundle though, and in the current configuration, it may well make initial page load (to something useful) slower due to multiple round trips to load script from the server.

I suggest that the home '/' and notfound pages be included in the initial js bundle by not chunking them.  It could also be worth evaluating what the performance benefit of chunking anything at all is;  the about and team pages are very small so the performance benefit to initial load may be negligible.

## 🔦 Context

The initial page load is followed immediately by another "loading" whilst the home bundle loads.  I'd rather wait a tiny bit longer initially and get straight to the home content.

**Comment by ivan-aksamentov** [comment]
@rcbevans Thanks for reviewing, Rich. Yeah, it is currently suboptimal, but I wouldn't bother.
That being said, if you want - totally go for it!

We are currently lacking some critical features, like import and autorun and the app is quite ugly. So all the non-essential performance optimization will only be prioritized after those are sorted out.

**Comment by maktarsis** [comment]
@rcbevans @ivan-aksamentov 
is this still relevant?

if so, I can take this

by the way, there are no benefits from unchunk NotFound page but I agree about Home page.

**Comment by rcbevans** [comment]
Yeah, NotFound (hopefully isn't something people will be seeing, but unchunking Home and the splash screen at least would be good, since those are the two that everyone would be expecting to see.

**Comment by ivan-aksamentov** [comment]
@rcbevans @maktarsis I would concentrate on more useful stuff.

Also, splash will probably be seen  only once, until the "skip" checkbox is checked. But none of this matter, because with HTTP2 it is really a drop in the bucket.

**Comment by ivan-aksamentov** [comment]
I will close this because it did not pick up. Also it is not our concern right now.
