### ISSUE TITLE
'Confirmed cases past 3 days'

### ISSUE THREAD

**Issue by noleti** [neherlab/covid19_scenarios#154]
# 🙋 Feature Request

'Confirmed cases past 3 days' as currently plotted in the 'Cases through time' is likely intended to represent the measured number of infectious people (as color is the same as simulated Infectious). I assume the 3 days period is thus chosen based on the 'infectious period' = 3 standard setting. Would it be possible to adapt the aggregation period for measured infected if the user changes the 'infectious period'? That would then more appropriately match to the simulated curve of infectious (which is influenced by the period).

## 🔦 Context

I am trying to accomplish meaningful matching of observed vs simulated infectious for non-standard 'infectious period' values.

## 😯 Describe the feature

Adapt the aggregation window by infectious period

## 💻 Examples

Example: [1,2,3,4,5] cases were observed on day 1 to 5. Currently, they are aggregated to [1,3,6,9,10] regardless to the size of infectious period. For infectious period of 5, the following would be my proposed aggregated values [1,3,6,10,15]

## 💁 Possible Solution

Not sure if the 3-day aggregation is done on user side, or server. If done on the user side, the 'infectious period' should be used as window size. If the aggregation is done on the server side, this feature will be harder to implement.

**Comment by rneher** [comment]
thanks, @noleti. Good point and you are right that this is meant to match the `infectious`. The time window is currently hard coded in the client-side javascript:

https://github.com/neherlab/covid19_scenarios/blob/master/src/components/Main/Results/DeterministicLinePlot.tsx#L111

But we would need to decide how to deal with non-integers and put otherwise sensible bounds.

**Comment by noleti** [comment]
non-integers should be possible to approximate by using the decimal places as weight for the first value in the window. But that would change your logic somewhat, and likely not fit into your nice one-liner. The GUI currently does not allow to set non-integer values btw. The `i>2` check also seems to depend on `infectious period`

**Comment by noleti** [comment]
Another related point I realized re: matching observed infected to predicted infectious: real-world infectious measurements are likely by symptom-driven testing factor 5-10 times lower than the yellow line. This might confuse people who try to match predicted and observed infectious.

As detailed in the severity assumptions, for some age groups only 5-15% of cases show symptoms (but are still infectious, I assume). I also assume that those without symptoms appear in the solid yellow Infectious line (while they are infectious, i.e. 3 days). 
As testing numbers for people without symptoms are likely smaller (often symptoms are precondition for tests), the real-world measurements will also be lower (by factor ~5-10) if only people with symptoms are tested. While such a factor is not huge in log scale, it might still make sense to have some note on this in the FAQ, or a (toggleable?) second dashed yellow line to show the expected 'expected tested positive' number.

**Comment by rneher** [comment]
We are planning to fit to the reported number of deaths. The discrepancy between the increase in confirmed cases and the yellow line would then correspond to under-reporting. Maybe we should differentiate them by using different colors. Having reasonable parameters for initial Condition and R0 are on top of the list!

**Comment by noleti** [comment]
Another point on real-data points vs simulated (adding here because related): The real-world hospitalized/ICU count will never go down, as we require the data to be cumulative. The simulated hospitalized/ICU count is 'current hospitalized/ICU'. So the real-world data hospitalized and ICU might need a filter with appropriate window length as well?
