### ISSUE TITLE
Make tooltip text to arrange in columns responsively

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#159]
# 🙋 Feature Request

## 🔦 Context

Currently plot tooltips are very tall and obscure the entire plot.
Could we arrange the items in columns responsively?

In particular on mobile. See the work in https://github.com/neherlab/covid19_scenarios/pull/157

## 😯 Describe the feature

Switch tooltip display to columns when appropriate to use the space more efficiently

## 💁 Possible Solution

Media queries and react-sizeme? I don't know.

Related
https://github.com/neherlab/covid19_scenarios/issues/158
https://github.com/neherlab/covid19_scenarios/pull/157

**Comment by keevcodes** [comment]
@ivan-aksamentov  you're referring to this correct? 
<img width="281" alt="Screenshot 2020-03-24 at 08 36 23" src="https://user-images.githubusercontent.com/17259420/77399889-99c65000-6daa-11ea-9c49-2c1ea4159270.png">

**Comment by ivan-aksamentov** [comment]
@keevcodes yes!

**Comment by miksa1987** [comment]
@ivan-aksamentov @keevcodes I think this could maybe be done with media queries and customized Tooltip content in Recharts. I was thinking about dividing the content to two columns in mobile, so it wouldn't be as tall as it is now. I can experiment with this today. We just need to be careful to not make it too wide to not overflow the screen horizontally.

**Comment by keevcodes** [comment]
@miksa1987 are you wanting to take care of this now? A two column layout would certainly help, however maybe setting an opacity to .6 or .7 to the toolbar could help?

**Comment by miksa1987** [comment]
@keevcodes Yeah, I can take this, as it's related to my PR I'm working on: [#157](https://github.com/neherlab/covid19_scenarios/pull/157)

I'm not completely sure about setting the opacity, but I can experiment with that too.

**Comment by ivan-aksamentov** [comment]
@miksa1987 as an additional feature, can you also align all numbers on the right side and remove columns (`:`) after names?  I think that will make it more readable, sort of like a table.

**Comment by miksa1987** [comment]
@ivan-aksamentov it shouldn't be too big thing if my styling will work normally inside the Tooltip. 

However I think If I divide the Tooltip into two columns on mobile, it could potentially have negative effect on readability. But on the desktop though, it might work well. Anyways, we should try this in action to see how it works.

**Comment by miksa1987** [comment]
@ivan-aksamentov Actually you were right, even though it's on 2 columns it's more readable when everything is aligned to the extreme sides. I just commited to my PR, I guess it is like you meant it?

**Comment by ivan-aksamentov** [comment]
This was mostly solved in #237
