### ISSUE TITLE
Update the Github repository to match modern standards of open-source software

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#16]
This may include:
 - Improve readme, add more details on how to run the app in dev and prod mode, in docker or without
 - Add Contributing guide
 - Add Code of conduct
 - Add Issue templates
 - Add Pull request template

See also:
  - https://opensource.guide/

**Comment by rsharvill** [comment]
Hi @ivan-aksamentov , I would love to work on this to begin contributing to the project if possible!

**Comment by ivan-aksamentov** [comment]
@rsharvill 
Hi Rachel, I've just merged a pull request addressing some of the concerns here
https://github.com/neherlab/covid19_scenarios/pull/57
Feel free to take a look. Whether you have some improvements in mind or some new proposals, we'd be happy if you could contribute!

I'm not sure what kind of contributions you are interesed in the most, but specifically for community-related setup:
 - We are thinking what to put into README.md, and what pages maybe to add to the app itself. 
 - We need documentation and guides for users, developers, data maintainers etc
 - Also, we definitely need a public chat (instead of issue #18), but we don't know which and how. 
 - Also we are looking for data curators from different countries, there  is now a PR that adds translations. So we also need translators.

But again, we don't necessarily know how to organize all that and are busy with other issues.

In general we want to grow a community and allow this community to be productive, so that contributions are easy and enjoyable. Any input is welcome here.

Otherwise, we still have a variety of [issues submitted](https://github.com/neherlab/covid19_scenarios/issues) and there are probably even more issues still hidden from us :)

**Comment by ivan-aksamentov** [comment]
Some additional thoughts:

 - I would like for new PRs and issues to have a choice dialog, that allows to pick a type of the PR or issue, then redirect to the appropriate template and assigns appropriate labels.

 - We need more details in Contributing.md about how to fork and make PRs, for newcomers

**Comment by rsharvill** [comment]
@ivan-aksamentov Sounds good! I am beginning to look through the project so I can get a better understanding of what you guys are working on.

Would you have time for a voice call or chat (through something like discord or slack) so I can be brought up to speed on the project itself and your goals?  I find I learn better that way. Let me know, thanks for being so responsive!

**Comment by ruisaraiva19** [comment]
@ivan-aksamentov @rsharvill I would also love to contribute with documentation and PR/issue templates.
I started contributing to open-source for the past couple of weeks and it's tuff when there is little to no documentation to get started with contributions.
This project seems a good starting point to deep dive into the open-source software standards.

**Comment by ivan-aksamentov** [comment]
@rsharvill @ruisaraiva19 

Great to have you on the project!
Carry on, you have a full freedom to experiment here!
Let me know if you need anything.

Feel free to join our new Spectum chat:
https://spectrum.chat/covid19-scenarios/general/questions-discussions~8d49f461-a890-4beb-84f7-2d6ed0ae503a
it's a bit empty right now.
Let me know if you have any ideas on how to make people less shy :)

There are many questions and ideas scattered across issues and in issue #18. I wish we could somehow gather everyone in one place.

**Comment by ruisaraiva19** [comment]
Just joined the chat.

We can start by updating the issues templates config `contact_links` with the Spectrum chat for questions and discussions.

Next, we would need to somehow move the questions/discussions from the #18 issue to the chat as well.

**Comment by ivan-aksamentov** [comment]
Yes, this sounds reasonable.
If you want to post anything anywhere from my name, send me a snippet and target location :)

Here is the HTML snippet for the  chat button. Feel free to randomly post it everywhere.

```
<p align="center">
  <a
    alt="Link to join the chat"
    href="https://spectrum.chat/covid19-scenarios/general/questions-discussions~8d49f461-a890-4beb-84f7-2d6ed0ae503a"
  >
    <img
      alt="Image for the link to join the chat"
      src="https://user-images.githubusercontent.com/9403403/77235704-691ec480-6bb8-11ea-985d-82ec87cfdcdf.png"
    />
  </a>
</p>
```

**Comment by ruisaraiva19** [comment]
PR with the Spectrum chat link ready for review.
Next, I will update/add issue templates with appropriate labels, base title, suggestions, etc.

**Comment by ruisaraiva19** [comment]
PR with issue templates for bug reports, feature requests, and documentation ready for review.

**Comment by ivan-aksamentov** [comment]
@ruisaraiva19 You are doing an incredible job, thank you!
In fact it's so good that today we have an influx of devs so large that I cannot keep up with all the PRs and issues. Oh well, first-world problems :)

**Comment by ruisaraiva19** [comment]
@ivan-aksamentov I'm glad I could help 👌.

**Comment by ivan-aksamentov** [comment]
I think we are doing much better now. I will close this issue, but if you have any suggestions, don't hesitate to open a new issue.
