### ISSUE TITLE
Trying to create scenarios for a single hospital

### ISSUE THREAD

**Issue by nataliadgepi** [neherlab/covid19_scenarios#162]
Hello,

Thank you for your wonderful model and great user friendly interface. I was wondering if Canadian data on cases could be added, specifically for each province. There is an open data source with all cases reported for each province here: COVID-19 Canada Open Data Working Group. Epidemiological Data from the COVID-19 Outbreak in Canada. https://github.com/ishaberry/Covid19Canada. (Access Date).

Also is there a way to see when ward beds would be maxed out (max hospitalizations) not just ICU? Is there a way to see how many vents are available? 

Do you know of any PPE forecasting models?

Thank you for all your great work!!!
Natalia

**Comment by ivan-aksamentov** [comment]
@nataliadgepi 
Hi Natalia, thanks so much for your suggestions. 
I will let Richard and Nick to answer this.
CC: @rneher @nnoll 

Regarding the data, the work is being done in a separate repository:
https://github.com/neherlab/covid19_scenarios_data

I created an issue there dedicated to the data from Canada:
https://github.com/neherlab/covid19_scenarios_data/issues/36

If you are available for implementing this yourself, then check out our [Data Contibutor's Guide](https://github.com/neherlab/covid19_scenarios_data#contributing-and-curating-data) and don't hesitate to open a pull request!

We look forward to your further suggestions!

**Comment by nnoll** [comment]
Thank you so much for your contribution!

Regarding your first point, we can easily add the Canadian province cases, provided a parser for the data source you've linked to is written. Check out https://github.com/neherlab/covid19_scenarios_data for a description of what we need. I invite you to open a separate issue there. 

As of now the hospital beds don't explicitly factor into the model -- it is simply a guideline for the eye. We have considered modeling finite hospital beds in a similar fashion as to how we model finite ICU capacity now but we haven't convinced ourselves that it will make a large enough qualitative difference for the complexity added. However, we are open to contributions in this direction! 

Ventillators or PPE forecasting are also not included at this time. Would you like to expand a bit on your use case? I would love to help you out with what you are trying to accomplish as this helping hospitals predict their needs is exactly what we hope to accomplish.

**Comment by nataliadgepi** [comment]
> @nataliadgepi
> Hi Natalia, thanks so much for your suggestions.
> I will let Richard and Nick to answer to this.
> CC: @rneher @nnoll
> 
> Regarding the data, the work is being done in a separate repository:
> https://github.com/neherlab/covid19_scenarios_data
> 
> I created an issue there dedicated to the data from Canada:
> [neherlab/covid19_scenarios_data#36](https://github.com/neherlab/covid19_scenarios_data/issues/36)
> 
> If you are available for implementing this yourself, then check out our [Data Contibutor's Guide](https://github.com/neherlab/covid19_scenarios_data#contributing-and-curating-data) and don't hesitate to open a pull request!
> 
> Feel free to explore our previous proposals:
> https://github.com/neherlab/covid19_scenarios/issues
> 
> and previous data proposals:
> https://github.com/neherlab/covid19_scenarios_data/issues
> 
> and to join the chat:
> https://spectrum.chat/covid19-scenarios/general/questions-discussions~8d49f461-a890-4beb-84f7-2d6ed0ae503a
> 
> We look forward to your further suggestions!

Hi Ivan, 
Thank you for your quick reply! I would love to help adding Canadian, provincial data although there is quite a bit missing. I will start a chat under the link that you provided.

Thank you!
Natalia

**Comment by nataliadgepi** [comment]
Thank you for your quick reply!

> Regarding your first point, we can easily add the Canadian province cases, provided a parser for the data source you've linked to is written. Check out https://github.com/neherlab/covid19_scenarios_data for a description of what we need. I invite you to open a separate issue there.

I will add the provincial data under the issue created. Thank you.
>
> As of now the hospital beds don't explicitly factor into the model -- it is simply a guideline for the eye. We have considered modeling finite hospital beds in a similar fashion as to how we model finite ICU capacity now but we haven't convinced ourselves that it will make a large enough qualitative difference for the complexity added. However, we are open to contributions in this direction!

Fair enough. 
 
> Ventillators or PPE forecasting are also not included at this time. Would you like to expand a bit on your use case? I would love to help you out with what you are trying to accomplish as this helping hospitals predict their needs is exactly what we hope to accomplish.
I was wondering if you had or knew of an app that could calculate PPE for staff (by type). I realize this may be tough to forecast for different hospitals. I did find this tool https://files.asprtracie.hhs.gov/documents/aspr-tracie-hospital-ppe-planning-tool.pdf but not sure if anything else exists for SARS/COVID pandemics.

Just to clarify, I'm a chronic disease epi and have experience with clin epi so this is all very new to me. Thank you for your tremendous work, it is truly making a difference!

**Comment by Johan-A-M** [comment]
Just a comment from a clinician with minimal experience in this kind of modeling.
Wouldn't the forecasting of PPEs be extremely unreliable? I mean, in an ICU patient we could use up to 20-30 PPEs/day while unstable, and in another maybe 5. Also, if we're short on PPEs one day, I will act in one way to save material, but if we get a refill the next day, I might act in another way and visit the patient much more often. I really understand the idea that these needs would be great to predict, but I simply think that the pragmatic use "on the floor" would make the model to hypothetical/non-clinical to be of actual use. Sorry @nataliadgepi if I sound rude, that is really not my intention!

**Comment by nataliadgepi** [comment]
> Just a comment from a clinician with minimal experience in this kind of modeling.
> Wouldn't the forecasting of PPEs be extremely unreliable? I mean, in an ICU patient we could use up to 20-30 PPEs/day while unstable, and in another maybe 5. Also, if we're short on PPEs one day, I will act in one way to save material, but if we get a refill the next day, I might act in another way and visit the patient much more often. I really understand the idea that these needs would be great to predict, but I simply think that the pragmatic use "on the floor" would make the model to hypothetical/non-clinical to be of actual use. Sorry @nataliadgepi if I sound rude, that is really not my intention!

Hi Johan, you are not being rude at all! I get it, it's completely unpredictable. In a situation where they are planning clean/dirty floors, staffing for peak they would like max (+/-) estimates of PPE needed to see how far off they are or how soon they will run out. Ideally they would have stockpile and not worry but much of the stockpile has been stolen so need to use strategies to minimize use and figure out how soon they will run out.

**Comment by Johan-A-M** [comment]
> Hi Johan, you are not being rude at all! I get it, it's completely unpredictable. In a situation where they are planning clean/dirty floors, staffing for peak they would like max (+/-) estimates of PPE needed to see how far off they are or how soon they will run out. Ideally they would have stockpile and not worry but much of the stockpile has been stolen so need to use strategies to minimize use and figure out how soon they will run out.

@nataliadgepi We have had the same problem, staff stealing PPEs, it’s horrible.
Regarding the need for estimates for PPEs, were you referring to the ER, a general ward or the ICU?

**Comment by nnoll** [comment]
I'll close this in the interest of general housekeeping. But feel free to continue the discussion in our discussion tab!
