### ISSUE TITLE
IMPORTANT: Autorun: run the algorithm and update the plots automatically without clicking on Run button

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#17]
This may include:

  - debounce `run()` calls
  - hide feature behind the checkbox, disabled by default

Issues:

 * `formik` does not allow to subscribe to the form state changes. It requires submit to be called
 * `formik` does not expose the form state. We currently grab the state in validation callback, which arguably, is a hack
 * `formik` seem to be re-rendering the entire form on changing any field. This is a performance problem - In automatic mode editing fields is very uncomfortable.  There are ways to workaround it, but I don't want to introduce any more workarounds.

Solutions:
 - Replace `formik`  with `redux-form`? It will require quite substantial changes, for example reimplementing the validation.

I posted a cry for help in the Formik's chat:
https://spectrum.chat/palmer/formik/retrieve-values-without-submit-re-rendering-covid-19-scientists-need-help~d595a68c-2090-4a16-8a21-6f0772ff48e7

The following gif shows how on changing one value the entire form including mitigation plot is being re-rendered:

![Peek 2020-03-16 20-55 mp4](https://user-images.githubusercontent.com/9403403/76856275-3b055180-6853-11ea-8194-fd8c0ed0518f.gif)

**Comment by UnforbiddenYet** [comment]
@ivan-aksamentov you may check out [the Fokmik's author answer](https://github.com/jaredpalmer/formik/issues/1218#issuecomment-500225537) to the same question where he suggests the possible solution for auto form submission.

As for the optimization, I'd say using the [`<FastField/>`](https://jaredpalmer.com/formik/docs/api/fastfield) or custom [hook-based](https://github.com/jaredpalmer/formik/issues/1026#issuecomment-524594409) implementation should prevent form fields wasted renders.

**Comment by ivan-aksamentov** [comment]
@UnforbiddenYet 
Hi Dmytro,
Thanks so much for the info. I will look into the Jared's example and the `FastField`.

**Comment by benjwexler** [comment]
Hey @ivan-aksamentov, Formik does expose the form’s values as part of the `formikBag` in the render method. Why not add an `onChange` to the Form component like this?

          {({ values, errors, touched, isValid }) => {
            const canRun = isValid && severityTableIsValid(severity)
            return (
              <Form
                onChange={(ev) => {
                  const { name, value } = ev.target;
                  const newValue = {};
                  newValue[`${name}`] = value;
                  const newValues = Object.assign(values, newValue);
                  handleSubmit(newValues)
                }}
                className="form"
              >

**Comment by ivan-aksamentov** [comment]
The work is being done on #90, but there are performance issues. Are there any React performance experts in the club? :)

**Comment by ivan-aksamentov** [comment]
@benjwexler thanks! I did not know this exists. We may try that.

**Comment by gj262** [comment]
I also see the lag with the changes in PR #90. But the change looks right if the lag can be addressed. I'll dig into what is getting called (unless someone is already doing so...).

CC: @ivan-aksamentov

**Comment by ivan-aksamentov** [comment]
@gj262 I don't know if anyone else is working on it other than @3b3ziz , but this is one of our top priorities, so go ahead and give it a good try :)

**Comment by gj262** [comment]
Once the graphs are drawn interactivity with the form is impaired. And this is regardless of manual Run click or auto Run. Just focusing different form inputs is sluggish. Stepping the counters is v. sluggish.

I'd be interested if this is seen by others with the current production site.

**Comment by rcbevans** [comment]
I added a [PR](https://github.com/neherlab/covid19_scenarios/pull/170) for this using debouncing and react hooks.

The performance seems good to me, can be tried at https://covid19-scenarios-git-fork-rcbevans-autorunsimulation.covid19-scenarios.now.sh/

**Comment by rcbevans** [comment]
> Once the graphs are drawn interactivity with the form is impaired. And this is regardless of manual Run click or auto Run. Just focusing different form inputs is sluggish. Stepping the counters is v. sluggish.
> 
> I'd be interested if this is seen by others with the current production site.

I'm seeing sluggishness doing any kind of manual entry of values for population count etc, both using the value steppers, and typing, because of the 4 deep object copies which happen every time the form is validated:

```
    // NOTE: deep object comparison!
    if (!_.isEqual(allParams.population, newParams.population)) {
      scenarioDispatch(setPopulationData({ data: newParams.population }))
    }
    // NOTE: deep object comparison!
    if (!_.isEqual(allParams.epidemiological, newParams.epidemiological)) {
      scenarioDispatch(setEpidemiologicalData({ data: newParams.epidemiological }))
    }
    // NOTE: deep object comparison!
    if (!_.isEqual(allParams.simulation, newParams.simulation)) {
      scenarioDispatch(setSimulationData({ data: newParams.simulation }))
    }
    // NOTE: deep object comparison!
    if (!_.isEqual(allParams.containment, newParams.containment)) {
      scenarioDispatch(setContainmentData({ data: newParams.containment }))
    }
```

In my PR I added a debounce to the validation of 500ms which feels like improves performance substantially, but once the debounced function triggers, the page still stutters.

**Comment by gj262** [comment]
What I ended up noticing was that the entire Main component tree re-renders for every click in the form(ix). And that is OK when the left hand side graphs are not present but quite slow when they are. 

Both PRs #90 and #170 give the desired autorun functionality. Though I did not see overlapping validation calls with normal interaction so would not necessarily think debounce is required at present. But no harm? 

In any case. One of PRs #90 + #170 coupled with #171 should give the desired autorun behavior with reasonable form interactivity.

**Comment by gj262** [comment]
And as previously noted, though maybe for another issue/time, using onChange would be a better hook for this over validate.

**Comment by 3b3ziz** [comment]
Sorry for being late.

I have tried debouncing multiple times but I am not convinced with it since that other than the population field, all fields ranges in small values so debouncing with 2 seconds would add a latency that is not needed.

I thinks we might debounce the onChange of that field specifically instead of debouncing the whole calculation.

@ivan-aksamentov @gj262 @rcbevans what do you think?

**Comment by rcbevans** [comment]
I am triggering a debounced run from statechanges to scenarioState using the useEffect hook, which is effectively the same as onChange.  The change to debounced the onValidate was to improve the performance of the UI when toggling custom values since it's doing four deep object comparisons on *each* validate.  That change, in and of itself, is unrelated to the implementation of autorun.

**Comment by gj262** [comment]
It looks like #170 & #171 are merged and so this can be closed now. Please re-open if I've missed something.

**Comment by dkozar** [comment]
Are you sure the form is a bottleneck?

I commented out the debounced part, and am "console.logging" the received value:

![image](https://user-images.githubusercontent.com/1078403/78514962-d8e1a180-77ab-11ea-9f9c-a7cfefa3220e.png)

Even without any debouncing, I feel this part is pretty snappy.

So I don't think the retrieval of form values is a bottleneck, but what is getting executed upon.

**Comment by dkozar** [comment]
I'm playing with possible fix in this PR: https://github.com/neherlab/covid19_scenarios/pull/432/

(this is WIP, not polished yet)

The general idea is to keep latest params in memory (Singleton) during the debouncing period, and to allow components to fetch them when needed. Because sending them through the store causes re-rendering of everything.

Demo (test for comparison): https://covid19-scenarios-97ywlzg4y.now.sh/
