### ISSUE TITLE
Modify the model to allow for non-exponential latency periods.

### ISSUE THREAD

**Issue by nnoll** [neherlab/covid19_scenarios#182]
# 🙋 Feature Request

I want to generalize from an exponential distribution of latency time to a modifiable Erlang distribution that more accurately recapitulates measured distributions.

## 🔦 Context

Currently the exposed class models the latency period between exposure to an individual infected with COVID-19 and becoming ill. With a singular state, the distribution of times is exponential which is a bad fit to the data, e.g. see [here](https://annals.org/aim/fullarticle/2762808/incubation-period-coronavirus-disease-2019-covid-19-from-publicly-reported).

In short, we are both overestimating the variance and the number of quick infection cases. This makes a qualitative difference as to where the peak/apex of cases lies which is entirely relevant for hospital planning resources.

## 😯 Describe the feature

Note this is very much related to Issue #26, however the distribution is not able to be arbitrarily edited by the user. Similarly, this is related to Issue #116, however it would not require shifting to a DDE (delayed differential equation).

## 💻 Examples

N/A

## 💁 Possible Solution

We internally increase the number of exposed states to a small cascade of 2/3 states as the distribution of the sum of exponentials is an Erlang distribution. In the future, we can consider making this tunable.

**Comment by nnoll** [comment]
I open this to start a discussion. If this seems good, I'll implement it.

**Comment by rneher** [comment]
Yes, would be a useful addition. I don't think we would need more than 2-3 states. One could also branch this to implement superpositions of distributions of different width.

**Comment by alo8** [comment]
Yes, using a cascade of states will make the simulation more realistic.
With just one exposed state we have a exponential distribution. The rate parameter for this distribution is equal to 1/T, with T being the incubation time.  
If we use a cascade of s states, we will get a Erlang distribution as pointed out by @nnoll .
The rate parameter of this Erlang distribution is s/T and the shape parameter is equal to s.
This final distribution will have a mean of T (as expected) and a variance of:
<img src="https://latex.codecogs.com/gif.latex?\frac{T^{2}}{s}" />
So if we would use an infinite number of cascades, the variance would become 0 and the Erlang distribution would become a delta distribution centered around T. This is exactly the proposal #116 (delayed differential equation). So by variation of the cascade number s, we have a way to gradually translate one proposal into the other.

But which casade numer s is the most realistic? 
@rneher proposed 2-3 states. If we look at the [literature](https://annals.org/aim/fullarticle/2762808/incubation-period-coronavirus-disease-2019-covid-19-from-publicly-reported?_ga=2.135677048.85260512.1586000715-1968856026.1586000715#article-top) a good fitting Erlang distribution for the incubation time has a shape parameter of 6 and a rate parameter of 0.88. Given that, we should use a cascade of 6 states and a incubation time of  6.82 days.

**Comment by alo8** [comment]
To improve the model in general, cascading states can be introduced not only to incubation time, but for all other state transfers (hospitalized, critical,...) also. 
Another interesting question would be if a Erlang distribution is fine or if we should strive for some Log-Normal distribution or some other... What is you opinion?

**Comment by nnoll** [comment]
@alo8 I was comfortable making this change because I was presented literature on measured latency periods from Wuhan. Before making this a general feature of the model, I would like to see data on the distributions of other times. Do you know of any?

**Comment by alo8** [comment]
@nnoll Not so easy to find good data for the distributions. In this [paper](https://www.thelancet.com/action/showPdf?pii=S0140-6736%2820%2930566-3) one can get at least the mean and also min/max values for all important state transfers. From these values one can conclude somehow reasonable distributions. I think they will be at least better than a pure exponential or a pure delta distribution.

**Comment by nnoll** [comment]
@alo8 yeah that's my worry. I think this could indeed be a more general
solution plugged in elsewhere, but I would wait until we have good sourced
data on the *variance* of these distributions before change the simulation
for everyone. However, after we release the current version, it would be
nice to revisit this idea in the context of a more "advanced" input page
where the user could specify the number of cascading states for each
compartment to use (should definitely not be in the default page which is
fairly technical as is).

**Comment by alo8** [comment]
@nnoll yes, the min/max values give only a glimpse on the variance.
A couple of days a go I stumbled opon this [simulator](http://covidsim.eu).
I am not sure if you know it already. If you switch to version 1.0 (top left, next to logo) you can choose (under advanced options) the number of stages used in that simulation. I assume they use a similar model.
