### ISSUE TITLE
Results plot is broken in German and Portuguese translation

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#199]
# 🐛 Bug Report

Results plot is broken in German and Portuguese translation

## How to reproduce

Steps to reproduce the issue:

 1. Clear local storage. Open the application in a browser. Confirm the disclaimer.

 2. Run the algorithm. Observe results plot is functioning normal.

 3. Switch to German locale. Observe results plot is broken.

 4. Same for Portuguese.

## 😯 Current Behavior

In German and Portuguese locale lines on results plot are squished to X axis. Y axis shows different numbers. All other locales are fine.

## 🤔 Expected Behavior

Plots should look the same in different locales (barring the format of numbers and text labels)

## 🌍 Your Environment

| Software      | Version(s) |
| ---------------- | ----------   |
| Browser       | Chrome 80 |

English:
![Screenshot from 2020-03-25 10-21-59](https://user-images.githubusercontent.com/9403403/77521182-8e465800-6e82-11ea-9724-4bfd005c0fbc.png)

German:
![Screenshot from 2020-03-25 10-22-24](https://user-images.githubusercontent.com/9403403/77521188-91414880-6e82-11ea-952c-5a72973fa85a.png)

**Comment by rcbevans** [comment]
I'll take a look at this too.

**Comment by rneher** [comment]
this has a trivial fix, see PR #209
