### ISSUE TITLE
Rounding

### ISSUE THREAD

**Issue by robjohnnoble** [neherlab/covid19_scenarios#2]
A minor issue: Peak hospitalisations should be given to the nearest integer (i.e. "Number of individuals") in the lower bar chart, in which the other variables are already rounded. I think you could do this by adding `round()` on line 40 of `PlotAgeAndParams.tsx`. Relatedly, `agesFrac` in the upper bar chart could be given to fewer significant figures.

**Comment by nnoll** [comment]
Thanks Rob! Both issues should be fixed on master now.
