### ISSUE TITLE
IMPORTANT: Changes in severity table do not trigger autorun

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#200]
# 🐛 Bug Report

When autorun checkbox is enabled, changes in the form or in mitigation graph correctly trigger autorun. However, when values in severity table are edited the run not triggered. The "Run" button is also disabled in this case, so there is no way to manually trigger rerun.

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser

 2. Check autorun checkbox

 3. Expand severity table card and edit values in the table. Observe no changes are in the plot.

## 😯 Current Behavior

Changes in severity table do not trigger autorun

## 🤔 Expected Behavior

Changes in severity table trigger autorun

## 🌍 Your Environment

Any

## Related:

 - https://github.com/neherlab/covid19_scenarios/pull/170

cc: @rcbevans Rich, you know more than anyone else about this feature. Could you please take a look?

**Comment by rcbevans** [comment]
Sure.
