### ISSUE TITLE
Setup proper infrastructure and continuous integration

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#21]
We need to figure out at least the basic infrastructure:
 - automated builds and deployment to production from `release` branch
 - automated builds and deployment to staging from `master` branch
 - automated builds and deployment of pull requests

TODO:
 - create domain names for production and staging
 - setup Travis or CircleCI, deploy on pushes

**Comment by Shrinidhikulkarni7** [comment]
Can we use Github actions instead of travis or CircleCI?

**Comment by kibertoad** [comment]
@ksatirli In case you wanted to save the world, now might be your chance.

**Comment by ivan-aksamentov** [comment]
@Shrinidhikulkarni7 sorry, I am not wevry familiar with GitHub Actions, but wanted to learn!

Right now we've got Travis CI that tests, builds and deploys to AWS and we've got now.sh deploying pull requests.

I know that GH Actons can do so many more. So can we combine?
I would like to have various automatic PR checks and bots, as bigger open-source projects have.

Any help is welcome here! Let me know if you need something to be set up in order to  proceed.

**Comment by ivan-aksamentov** [comment]
@kibertoad @ksatirli , yep that's the best opportunity your life, folks! Contributions welcome :)

**Comment by Shrinidhikulkarni7** [comment]
Hey @ivan-aksamentov  it looks good as of now.
I can dockerize this project if you need me to.

**Comment by ksatirli** [comment]
@ivan-aksamentov what kind of actions are you thinking of? Are you looking to move the steps in [travis.yml](https://github.com/neherlab/covid19_scenarios/blob/master/.travis.yml) to a GitHub Actions Workflow?

**Comment by ivan-aksamentov** [comment]
@ksatirli No, I am quite happy with the current Travis setup right now. That is unless you have any tweaks and suggestions in mind.

I am looking to maybe augment the current setup with things that Actions can do, but Travis cannot. There are so many triggered PR checks exist out there. Also there are active, contributing PR bots.

For example, I am planning to integrate I want to integrate browserstack, snyk, dependabot etc. 

Can actions help to automate release process? To tell devs to re-format code and to tel them when it is time to rebase?

In fact, I'd be cool if you tell me what is out there exist to automate things and to help to ship better things.

**Comment by kibertoad** [comment]
@ivan-aksamentov @ksatirli 
One thing that I dislike about Travis is how repeated executions on same PR often result in significant waiting in queue time, which is not the case with CircleCI (not sure how it is with GitHub Actions).

To chime in on beefing up CI: I don't think you need snyk or lighthouse bots, both of those can be executed programmatically from npm as a part of the build process, see https://www.npmjs.com/package/lighthouse-ci

Now the obvious gaps that I'm currently seeing:

1) ESLint is not executed in CI;
2) TSLint is not executed in CI (not sure if it is even needed - isn't it redundant when ESLINT-Typescript is used, and considered obsolete overall?);
3) Stylelint is not executed in CI;
4) No snyk
5) No dependabot/greenkeeper/renovate
6) No code coverage calculation with coveralls

One thing that I would beg you not to add is branch-name/commit message/PR title validation. Every single time I've seen those added, there was lots of frustration from external contributors and overall eagerness to contribute dropped.

**Comment by kibertoad** [comment]
This also looks interesting - https://deepscan.io/ - but I've never used it before.

**Comment by ivan-aksamentov** [comment]
@kibertoad yeah, I considered CircleCI too. It just required some more setup in terms of accounts and I did not wanted to bother Richard, he was very busy at that time.
I guess we could migrate, I am not against it.

Linters are not executed due to the fact that we've got like 500 errors there... Hence: https://github.com/neherlab/covid19_scenarios/issues/101

Coverage.. well you saw the state of the testing. But I guess it is not time to set it up.

Do you think you could help me to sketch a config for CircleCI? Does it make sense to run in a container? And we could start adding all this stuff little by little.

Feel free to create a draft PR and a thread in the chat.

**Comment by ivan-aksamentov** [comment]
@kibertoad I've got CircleCI account running and it is waiting for a config file. Would be fantastic if you could sketch a first draft. I need to do something else, but will join later.

**Comment by ivan-aksamentov** [comment]
This was resolved
