### ISSUE TITLE
Exporting and visualization

### ISSUE THREAD

**Issue by nataliadgepi** [neherlab/covid19_scenarios#218]
Hello, 

Your tool is absolutely amazing. I would like to present it to exec ppl at hospital, those in charge of decision-making. I'm not a data viz expert, would it be possible to export the model output along with a pdf or worksheet /HTML with the interactive graph so that it could be used by others without having to enter the parameters all over again? Someone who saw it today was so impressed they want to send it all the way up to the federal level. 

Also is there a source for some of the assumptions made by the model (contacts between people) , level of mitigation (how is this measured, what does each value mean, do you have references)? 

Thank you!!!
N

**Comment by nnoll** [comment]
Related Issue #110

**Comment by ManuelB** [comment]
I created a simulation based on localized data for Germany including a visualization with kepler.gl:
https://github.com/ManuelB/covid-19-vis

A video how to create your own is here:
https://youtu.be/lwUDvNfVeEo

For the newest status I added real-time data and  validated the simulation with hospital beds on district level:
https://kepler.gl/demo?mapUrl=https://raw.githubusercontent.com/ManuelB/covid-19-vis/gh-pages/simulation/2020-03-27_Landkreise_Intensivbetten_Strong_Mitigation-3-month-keplergl.json
