### ISSUE TITLE
Cloud based syncing/backup of scenarios/user preferences

### ISSUE THREAD

**Issue by rcbevans** [neherlab/covid19_scenarios#222]
# 🙋 Feature Request
Add a mechanism of backing up/restoring using preferences and configured scenarios to the cloud for use across multiple clients.

## 🔦 Context
Roam my preferences and custom scenarios with me.

## 😯 Describe the feature
Add login/logout which will synchronize the values in LocalStorage to a cloud based data store.  On login, these cloud values will be pulled, replacing/merging with current configuration.

## 💁 Possible Solution
Firebase has an all in one auth/signup/social media sign in, and a very very easy to use json based realtime database which can be used in a very similar manner to LocalStorage, and can even fire events on cloud database updates, making realtime sync across devices seamless.

**Comment by miksa1987** [comment]
@rcbevans I could try implementing this? I think this could be done with Firebase auth and Firestore, as I find Firestore even easier to use than Realtime database.

Some points I'm thinking:
- There could be a users collection, where a document is created when user is created, with the document id being the user's uid.
- On logging in, the user's data is fetched from the document, which is found by the user's uid.
- The values are put into localStorage, and whenever some of those values are updated, they will be also updated to Firestore.

At first I could just do an email signin, we could check out other signin options later.

**Comment by rcbevans** [comment]
We might need someone at neherlab to create and maintain ownership of the firebase account.  @ivan-aksamentov?

Some things to think about:

The login/logout, and fresh start of data experience.
We'll need some kind of privacy policy, and GDPR compliance, allowing users to obtain/delete their data freely.

We want to be very careful around user credentials, if doing email/password based login (I always prefer oauth based login for this reason, so I never have to touch a password).

**Comment by rcbevans** [comment]
Also think about the multi-scenario, and consider that when designing the data structure.

Most important is ensuring that the firestore has role based access controls so users can only read/write their own user data.

**Comment by miksa1987** [comment]
I could experiment with my own Firebase account, it could be probably easily switched to neherlab's by using environment variables. Of course, neherlab account should have auth and firestore ready when starting to use that.

Regarding user experience, I was thinking about a login/logout button somewhere on top of page, that would trigger a popup form for login(like the disclaimer when arriving to the site). The account creation form would be something similar.

I'm wondering if there should be some kind of indicator for being logged in, where the user could go to check/delete their data? Maybe an additional component for the top bar which could house the login/logout button as well?

Of course, we should be careful with user credentials. I was thinking that they should only be handled by the login form, and pass them to Firebase. And other than that, if user information is needed, use the currentUser's uid for that. That way it would probably be easier to add different login methods. Also, I think that Firestore's security rules are good enough for ensuring that users can only access their own data?

I thought a little about the multi-scenario, I'm starting to think that it would probably be easiest to create a different collection for scenarios, with each scenario having a uid for linking it to a certain user. What do you think about that? I'm thinking that way it's also easier to make changes to scenarios' data structure if needed.

**Comment by rcbevans** [comment]
Working on your own is fine for dev, but need to make sure the build system is ready to provide an 'official' firebase auth key etc for preview builds/production deployments.

A lot of websites use a hero icon in the top right which you can click to bring down a context menu, or a side panel with some additional properties/settings and UI customizations.

The side pane could include login/logout, download my data, clear my data (with a warning that this will clear data across all logged in devices), access to review the disclaimer/privacy policy/GDPR disclaimer etc.  Could also add the ability to add a gravatar (another benefit of social login is the gravatar is instantly available to you).

The language toggle could also move into the menu pane?

Could also have the app use a hamburger menu style navigation, as an alternative design.

It would also be worth integrating a login/signup option on the splash screen.

**Comment by miksa1987** [comment]
Yes, that's why I was thinking about env variables. If done correctly, it should work for production/preview builds by just changing the variable values. 

I could start by putting an icon in the top right, where the language toggle is. Clicking on it would toggle a menu, which would have the options you mentioned. I think the language toggle should be there too, as it's related to user settings.

I think it would be a good idea to integrate login/signup to the splash screen. Maybe buttons which would take the user to corresponding form?

Thinking about improving the design, could it be a hamburger menu on mobile where there would be the About, Team, FAQ links? Although this shouldn't be a priority regarding this feature.

Then thinking about the data structure, what do you think about this:
- The values from localStorage saved to a document in users collection where documents are identified by uid.
- Scenarios in a different collection, and each document pointing to a user's uid.

**Comment by miksa1987** [comment]
Allright, so I'm _starting_ to get something together, you can see the progress here: [firebase-sync](https://github.com/miksa1987/covid19_scenarios/tree/feat/firebase-sync)

There's still A LOT of work to be done though, for example there's currently not much implementation done on data structures. And pretty much everything else.

**Comment by ivan-aksamentov** [comment]
This does not seem to be what we need anymore.
