### ISSUE TITLE
Replace autoscrolling with manually triggered scrolling

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#223]
# 🙋 Feature Request

I propose to remove current autoscrolling behavior. It is very annoying. I don't think anyone needs this on desktop.

In particular:
 - changing any form field scrolls on desktop (should not scroll at all)
 - blurring from severity table scrolls away from it, not allowing to continue the input into other fields (common case)

On mobile it's fine, but only because you cannot really do any decent job there anyways.
Our main focus is desktop.

## 😯 Describe the feature

 - [ ] Autorun does not trigger scroll
 - [ ] Run button does not trigger scroll
 - [ ] **In single-column mode only** "Go to results" overlay button appears near bottom edge of the screen whenever the result is available (wait for algorithm to finish!)
 - [ ] In all other layouts the button is not rendered (`null` or `hidden`? )
 - [ ] Clicking the button (and nothing else) triggers scrolling to the results section

## 💁 Possible Solution

Adapt current scrolling mechanism, but trigger only on explicit request from user and only on mobile. Use media queries for finding current layout? (align with bootstrap's breakpoints)

## Related

 - https://github.com/neherlab/covid19_scenarios/issues/71
 - https://github.com/neherlab/covid19_scenarios/pull/84
 - https://github.com/neherlab/covid19_scenarios/pull/103
 - https://github.com/neherlab/covid19_scenarios/issues/142
 - https://github.com/neherlab/covid19_scenarios/pull/179
 - https://github.com/neherlab/covid19_scenarios/pull/212

**Comment by rcbevans** [comment]
I'll pick this up
