### ISSUE TITLE
 Outcome Population average

### ISSUE THREAD

**Issue by Chrisx68** [neherlab/covid19_scenarios#229]
Thanks for this tool,, you all did a great job! Please find below a potential bug:

# 🐛 Bug Report
The Mild% result seems not to be correct.

## How to reproduce
Steps to reproduce the issue:
 1. Open the application in a browser, run any default scenario.
 2. Modify Severity assumptions and age-specific isolation table in a way that each age group has identical parameters: 
 3. Use the following parameters (any other can be used of course): 
     confirmed: 20%    severe: 30%   critical:   35%   fatal:  45%
     In this case, 100% - 20% x 30% / 100 = 94% should be mild cases

## 😯 Current Behavior
The result is (in my scenario)  91.56%. When adding to this 91.56% the critical% result (2.44%), this would end up in the correct result of 94%.

## 🤔 Expected Behavior
The expected result should be 94% mild cases.

**Comment by rneher** [comment]
Thanks, @Chrisx68, for pointing this out. You are right, the figure for 'mild' should be 1-'severe' but we in addition subtract 'critical'. We'll fix this asap.
