### ISSUE TITLE
Improve readability of the results graph tooltip

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#233]
# 🙋 Feature Request

### Presence
Currently lines in the tooltip appear and disappear depending on a value of a particular point on x axis. Making focusing on a particular line difficult. In particular, a line "ICU overflow" disappears when zero. Same with all "Confirmed" lines.

### Color
Additionally, some of the entries are colored such that they don't have a sufficient contrast on the white background. This somehow happens with the most important entries, such as "Deaths" and "Confirmed *".

## 🔦 Context

Some work is done in https://github.com/neherlab/covid19_scenarios/pull/157
After it merged, we can take a look at further improvements.

## 😯 Describe the feature

 - [x] All lines should be present at all times when hovering different parts of the plot.
 - [x] "Confirmed *" lines should say "-" as a value when a value is not present
 - [ ] (optional) "Confirmed *" lines  should be shown only if there is at least one value present in any of these lines. But they should be either all shown or all hidden. This is for regions without confirmed data.
 - [ ] Other lines should show "0" when a value is not present. For example "ICU overflow".
 - [x] Revamp color scheme to be more accessible (improve contrast ratio fg-to-bg)
 - [ ] (desirable) Make color scheme accessible for color blindness (use online generators and verify in Firefox https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector/Simulation)

## Related

 -  https://github.com/neherlab/covid19_scenarios/pull/157 (implements better positioning on mobile and arranging lines in 2 columns)

**Comment by kmid5280** [comment]
@ivan-aksamentov Regarding making the color scheme accessible, I found a way to make the lines dotted. We could potentially take similarly-colored lines and make them dotted or solid, or find other ways to differentiate them. Would that be a good start?

![dotted lines](https://user-images.githubusercontent.com/35879775/77815254-d9c55580-707e-11ea-9770-90e1a470a2f5.png)

**Comment by ivan-aksamentov** [comment]
@kmid5280 Hm, I am not sure.  Dotted lines change semantics, so that should be coordinated with our science team.
I summon @rneher  and @nnoll ! :sparkles:

**Comment by kmid5280** [comment]
@ivan-aksamentov Any further thoughts on this idea so far?

**Comment by gj262** [comment]
I will take a look at the first 4 tasks of this unless someone else is working on it? 
It should also help alleviate #234

**Comment by ivan-aksamentov** [comment]
Mostly resolved by #495
