### ISSUE TITLE
Improve positioning and movement of the results graph tooltip

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#234]
# 🙋 Feature Request

Currently the tooltip positioning is very chaotic. The smooth animations sometime work fine, sometimes the tooltip jerks and twitches like crazy.

![Peek 2020-03-26 18-26](https://user-images.githubusercontent.com/9403403/77680312-12d4cb80-6f94-11ea-93e0-b7103a44f269.gif)

## 😯 Describe the feature

This feature require some tweaking and checking the overall UX. Cannot give exact TODOs, but this would be nice to include:
 - [ ] prevent any jerkiness and twitching from happening. Partially addressed in https://github.com/neherlab/covid19_scenarios/pull/239
 - [ ] make tooltip follow the mouse without too much of a lag (or a little lag just to highlight the movement of the vertical indicator line on the plot)
 - [ ] disable as much animations as possible, to improve compatibility on different browsers and devices
 - [ ] z-index: prevent tooltip to be obscured by the text on  the graph below when overlaps
 - [ ] these numbers is the most important part of the application. Why are they in the tooltip?
 - [ ] be creative, try different things and approaches that lead to better UX

**NOTE**: we are talking specifically about tooltip and nothing else

## Related

 - https://github.com/neherlab/covid19_scenarios/issues/233
 - https://github.com/neherlab/covid19_scenarios/pull/157
 - https://github.com/neherlab/covid19_scenarios/pull/239

**Comment by kmid5280** [comment]
@ivan-aksamentov A few questions:
- Which animations are you currently aware are happening within the application?
- Can you provide steps to reproduce the issue with the z-index, where the text on the graph obscures the tooltip?
- You mentioned numbers in the tooltip. Which numbers are you referring to and what changes would you prefer?

**Comment by ivan-aksamentov** [comment]
@kmid5280 

> Which animations are you currently aware are happening within the application?

This issues is specifically about results plot tooltip. And I don't know which animations are enabled there. I think the default ones that come from the plotting library.

> Can you provide steps to reproduce the issue with the z-index, where the text on the graph obscures the tooltip?

You just move mouse around until the tooltip is positioned such that it goes outside of the plot on its bottom part:

![Screenshot from 2020-03-27 00-44-28](https://user-images.githubusercontent.com/9403403/77707002-344dab80-6fc4-11ea-936a-ab4b6f07bb84.png)

Because tooltip is quite chaotic, I don't really have exact steps.

> You mentioned numbers in the tooltip. Which numbers are you referring to and what changes would you prefer?

I meant that these results (numbers in the tooltip) are the ultimate results we want to show. Why do we hide them in a tooltip then?

We might meed to rethink that. Especially if a creative enough person suggests a better alternatve.

**Comment by kmid5280** [comment]
@ivan-aksamentov I wasn't able to reproduce the issue with the tooltip overlapping the bottom of the chart, but I do see that the tooltip will "drift" over the bottom for a brief second in some cases before traveling up. What may be happening is that the default animation of the tooltip is leading it to get "stuck" in some cases in positions it shouldn't be in. I found that for the Tooltip components, you can add an isAnimationActive property and set it to false. This will prevent the default animation of the tooltip, but it will be jerkier and may not be as visually appealing. Possible related info at https://github.com/recharts/recharts/issues/434.

**Comment by thoo1** [comment]
Thoughts on having a UI that combines the stats of each legend item and the legend itself?

Eg the number is displayed alongside the legend and is separate from the cursor

**Comment by ivan-aksamentov** [comment]
@thoo1 Yeah... maybe. I'm not a giant UX specialist.
It will probably take a lot of space. Especially on mobile, might be awkward.
Not a top priority right now, but feel free to try!

**Comment by ivan-aksamentov** [comment]
I was also thinking about "zoom the results" feature: https://github.com/neherlab/covid19_scenarios/issues/284

**Comment by maktarsis** [comment]
@ivan-aksamentov 

from my point of view, the best experience we can achieve is to get rid of tooltip on the chart and place it somewhere near the chart which will be visually accessible from any device.

Proposal clarification:
1) place a box nearby
2) display only when the mouse (finger) on the chart (or always)
3) show data dynamically considering where the mouse (finger) at the moment

**Comment by maktarsis** [comment]
I like the way it is implemented on small screens
https://prnt.sc/ropm71

✅ faster
✅ bug-free
✅ less frustrated and annoying

I just suggest placing it to the left of the chart for large creens

**Comment by gj262** [comment]
Digging into this a bit, I noticed that the tooltip component sometimes gets a payload of 0 or 2 items. It typically happens for a brief moment. And this causes the tooltip to render no tooltip or a small tooltip which 'jags' the position.

The two item payload is quite odd, I suspect some data spread weirdness going on somewhere...

```
[
  {
    "name": "time",
    "unit": "",
    "value": 1584662400000,
    "payload": {
      "time": 1584662400000,
      "cases": 14250,
      "observedDeaths": 150,
      "newCases": 9589,
      "hospitalBeds": 1485000,
      "ICUbeds": 49499,
      "susceptible": 328966104,
      "infectious": 227040,
      "severe": 4783,
      "critical": 2158,
      "recovered": 316346,
      "fatality": 308
    },
    "dataKey": "time"
  },
  {
    "unit": "",
    "value": 14250,
    "payload": {
      "time": 1584662400000,
      "cases": 14250,
      "observedDeaths": 150,
      "newCases": 9589,
      "hospitalBeds": 1485000,
      "ICUbeds": 49499,
      "susceptible": 328966104,
      "infectious": 227040,
      "severe": 4783,
      "critical": 2158,
      "recovered": 316346,
      "fatality": 308
    },
    "dataKey": "cases"
  }
]
```

**Comment by gj262** [comment]
One of the reasons the tooltip is rendering strangely is because the scatter plot elements can activate and deactivate the tooltip. This can be seen when you drag the mouse over the scatter but not always and it is typically brief causing the tooltip to disappear and reappear.

(See recharts:src/chart/generateCategoricalChart.tsx handleItemMouseEnter() handleItemMousLeave())

The easiest fix is to ignore pointer events for scatter plot elements. I'll create a separate PR to address that, which along with PR #495 should make tooltips super smooth.
