### ISSUE TITLE
Add popup on startup

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#25]
We want to add an initial modal popup with a sort of a "user agreement" info, and consent

 * non-liability disclaimer
 * eventually, GDPR compliance info and consent
 * eventually, local storage or cookies options, when we have those

**Comment by rcbevans** [comment]
Do you have any UI mockup for the how you want the dialog to look/what the text should be?

**Comment by rcbevans** [comment]
I have a basic bootstrap based dialog, with light-dismiss, and sample liability disclaimer text:

![image](https://user-images.githubusercontent.com/2041260/77144628-a44bb700-6a43-11ea-965c-26ff43e0b851.png)

It shows as part of the layout component when the component is first mounted.  I implemented it using just the bootstrap css classes, though it would be simpler if a dependency were taken on [react-bootstrap](https://www.npmjs.com/package/react-bootstrap).

**Comment by ivan-aksamentov** [comment]
@rcbevans 
Hi Rich, thanks!

Feel free to submit a PR! We are currently using [reactstrap](https://reactstrap.github.io/).

Honestly, not only we don't have a mockup, we haven't even yet figured what should be there as text. Mostly something long the lines of what there is already on the results card. Something like: "this is theoretical math and these are the human lives and also predicting the future is hard, so be careful", but more official :)

We may also need a GDPR disclaimer, because we may start storing the parameters and user preferences in local storage.

Not sure if we are crossing the line where we should add a FDA-style disclaimer that this is "not a medical device" for US folks out there.

In any case, if you have any thoughts, let us know.

I'll cc Richard @rneher, he may want add something.

**Comment by rcbevans** [comment]
Ah, didn't realize you had reactstrap.  In that case, there is already a nice component ready to be used which is cleaner than my css based implementation (not to mention likely more bug-free, and accessible friendly.

How does this issue jive with #107 for adding a landing page?  Is that preferred to a modal, or anticipated to be in addition to?

**Comment by ivan-aksamentov** [comment]
@rcbevans 
With popup in simulator we will gather consent once. I think we need an explicit action, like "I agree" checkbox. Then we store the consent version and skip the popup, until we release a new version of the app with a new version of disclaimer.Id new disclaimer version is greater than the one that is stored, show popup again.

Landing is purely cosmetic, we will have a checkbox to skip.

Does it make the first visit too annoying? Click on landing and then on modal.

**Comment by rcbevans** [comment]
If users come to the site, they're going to want the simulator; having to click through two dialogs to reach what they want could lose users at each step.

I think the modal shouldn't intercept navigations to the simulator.  Perhaps update the routes so the sim is at /simulator, and the landing page functions as a homepage at /.  I think the modal should show every time, but with a checkbox to not show again.

**Comment by rcbevans** [comment]
That way users can bookmark /simulator to jump straight to it.  I think it's a good idea to show the disclaimer if terms change, just need to ensure it doesn't happen *too* often, else it'll annoy.
