### ISSUE TITLE
Direct links from outside the app not working

### ISSUE THREAD

**Issue by noleti** [neherlab/covid19_scenarios#250]
# 🐛 Bug Report

A visit to https://neherlab.org/covid19/about from outside the app results in a 404 response, likely because the webserver does not know to redirect to the app?

## How to reproduce

Steps to reproduce the issue:

 1. Open https://neherlab.org/covid19/about in a browser
 2. Server will return 404

## 🤔 Expected Behavior

About page of the app should appear

## 💁 Possible Solution

Web server needs to know to redirect to app?

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System |
|                  |

## Related

 -

**Comment by rneher** [comment]
Yes, this is a problem with out current hosting situation. this will be resolved when we move to a proper domain. Should happen very soon!

**Comment by ivan-aksamentov** [comment]
@noleti Thanks, I confirm this is fixed on the master branch. We announce the new deployment soon™ :)
