### ISSUE TITLE
Including distribution of Latency & Infection period

### ISSUE THREAD

**Issue by Simulator1985** [neherlab/covid19_scenarios#26]
"Latency" & "Infection Period" in reality are not a single value but have pretty wide distribution what can impact the results significantly. Similar to Age distribution used for evaluation you can incorporate a simple histogram or function based distribution for  both terms.

But great Job, congratulations

**Comment by nnoll** [comment]
This is a great idea. In reality, we aren't simulating individual people so we don't have a clean way to assign actual recovery/latency times. In its current form, the model could only capture such effects by sampling the deterministic rates we currently use by a distribution that's not Poissonian. 

The code as written can easily accomodate stochastic sampling. The evolve function accepts a sampling function that you can program to do just this. If you (or anyone reading this) want to give a go at an input widget, I'll hook it up to the model in the branch and we can play around.

However, I personally think we should hold off on such a feature until we have a more detailed model that can directly plug into such an input.

**Comment by rneher** [comment]
We have implemented non-exponential distributions in #182 
Custom distributions would require agent based models.
