### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nnoll** [neherlab/covid19_scenarios#28]
The link to the Chinese CDC data from which our severity data is broken.

**Comment by ivan-aksamentov** [comment]
Yes, this is a very slow link to a website in mainland China, and sometimes it breaks.
We need to see if it can be replaced with a link to an archived snapshot.

**Comment by anandgraves** [comment]
The Internet Archive has a snapshot from march 20:
https://web.archive.org/web/20200320025420/weekly.chinacdc.cn/en/article/id/e53946e2-c6c4-41e9-9a9b-fea8db1a8f51
