### ISSUE TITLE
Typos in FAQ

### ISSUE THREAD

**Issue by t-eckert** [neherlab/covid19_scenarios#285]
# 🐛 Bug Report

Noticed a few misspellings in the FAQ portion of the site.

## How to reproduce

Load the FAQ page on the site.

## 😯 Current Behavior

The second answer includes the following spelling mistakes (in bold):

**COVID19** cases in critical condition need intensive care for a long time. Our model assumes that they spend on average **14days** in the ICU. The **severly** ill (our proxy for those in need of a regular hospital bed) either deteriorate fast or **recovery** (default in our model is four days). Hence at any given point in time, the number of critically ill people might exceed the number of **severly** ill.

The third and fifth answers also include "COVID19". I believe this should be "COVID-19" (though I am open to being wrong).

The final answer includes the text:

Their model is individual based, meaning their program represents a large number of individuals among **which** the virus is spreading. Our model **is breaks** the population into age-groups and different categories corresponding to susceptible, infected, dead, recovered, etc. This allows for faster simulations, but **looses** some realism.

## 🤔 Expected Behavior

The text in the first answer should read:

COVID-19 cases in critical condition need intensive care for a long time. Our model assumes that they spend on average 14 days in the ICU. The severely ill (our proxy for those in need of a regular hospital bed) either deteriorate fast or recover (default in our model is four days). Hence at any given point in time, the number of critically ill people might exceed the number of severely ill.

The text in the final answer should read:

Their model is individual based, meaning their program represents a large number of individuals among whom the virus is spreading. Our model breaks the population into age-groups and different categories corresponding to susceptible, infected, dead, recovered, etc. This allows for faster simulations, but loses some realism.

## 💁 Possible Solution

I fixed the typos in my fork, I just didn't want to issue a PR without context.

## 🔦 Context

Nothing personally, I just saw the typos. Thought they were worth fixing.

## 🌍 Your Environment

Probably not relevant

## Related

 
[My branch](https://github.com/t-eckert/covid19_scenarios/tree/fix/typos-in-faq)

**Comment by maktarsis** [comment]
I suggest creating PR and link to this issue
and the maintainer will already decide whether he needs it or not
