### ISSUE TITLE
e2e tests broke

### ISSUE THREAD

**Issue by maktarsis** [neherlab/covid19_scenarios#287]
# 🐛 Bug Report
After adding the landing page all e2e tests don't work at the moment

## How to reproduce

Run `yarn e2e:dev`

## 😯 Current Behavior
Tests don't work

## 🤔 Expected Behavior
Tests work.

## 💁 Possible Solution
I'm working on it now.

## 🔦 Context
The system should not have broken tests in `master`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System | Windows
|                  |

**Comment by whiver** [comment]
As the PR is open maybe the flag *help wanted* could be removed?

It's a bit hard to know which issue to work on as there is sometimes already someone looking at it, leading to this situation where 2 PRs have been created to solve the same issue. 😕
Is there a specific process to indicate that an issue is being addressed?

**Comment by maktarsis** [comment]
@whiver yeah, u r right

i'm still waiting until my PR got merged.

**Comment by maktarsis** [comment]
that's not cool

- ignoring
- all my changes were copied by other developers

ok, I don't want to take part in this
