### ISSUE TITLE
automatic bestfit of the past: automatic choose of all unknown parameter in such a way that the past is modelled in the best way, nearest to the already known data points

### ISSUE THREAD

**Issue by sourlier** [neherlab/covid19_scenarios#290]
# 🙋 Feature Request

## Related

 -
 -

**Comment by rneher** [comment]
we are working on this...

**Comment by nnoll** [comment]
This is now integrated within the data pipeline. I'll close this, but if you have a more specific suggestion, please open another Issue!

**Comment by sourlier** [comment]
Dear Nicholas

Fine … In fact, I recognize that it fits better than before, that’s true!

As far as I understand the automatism is active now all the time, this means there is NOT a special button to activate it (e.g. a checkbox).

Then I don’t understand how it works … e.g. , is the parameter R=2.7 determined determined automatically on the beginning only? I.e. , when I change it manually to e.g. R=3.0 then the resulting curves are calculated based on the manually changed value, without an automatism?

1.	In the case my assumption is true (automatism only on the beginning): which of all values are determined automatically from the given data points oft the past and which values are not?
2.	Is this really the optimal bestfit? 
I.e. is  there no other solution of the parameter set fitting closer to the given data values oft the past? It seems me quite a little away … ? But perhaps there is in fact no closer solution ?

Best regards
David

Original Request:
automatic bestfit of the past: automatic choose of all unknown parameter in such a way that the past is modelled in the best way, nearest to the already known data points (
Answer:
This is now integrated within the data pipeline. I'll close this, but if you have a more specific suggestion, please open another Issue!
------
MfG
Dr. David Sourlier
---------------------------------------------

Delta 3D GmbH

"Mathematics for Metrology"

Gäwisstrasse 8

CH-9633 Hemberg (SG)

Switzerland

---------------------------------------------

T: 071 377 17 17

F: 071 377 10 30

N: 079 525 44 55

info@delta-3d.com

http://www.delta-3d.com

---------------------------------------------

* numerische Modellierung

* numerische Simulation

* nichtlineare Optimierung

---------------------------------------------

math.-phys.

* Software

* Beratung

* Entwicklung

* Analysen

* Simulation

---------------------------------------------

* Optische Messtechnik

* Laser-Messtechnik

* Koordinaten-Messtechnik

* Maschinen-Kalibration und -Kompensation

---------------------------------------------

Software

---------------------------------------------

* FUNKE, universelle Bestfit-Bibliothek

  für Koordinaten-Messtechnik und Reverse-Engineering

* Mess- und Konstruktions-Software für CNC-Rohrbiegemaschinen

* Photogrammetrie-Software

* Positions-Erfassung

* Kunden-spezifische Mess- und Kalibrier-Software

---------------------------------------------

Hardware

---------------------------------------------

* Infrarot D3D-Rohrgabelsonden

* ShapeTracer Laserscanner

* Messarme

* LASEC Black-Box

---------------------------------------------

 

 

Von: Nicholas Noll <notifications@github.com> 
Gesendet: Mittwoch, 1. April 2020 22:13
An: neherlab/covid19_scenarios <covid19_scenarios@noreply.github.com>
Cc: sourlier <info@delta-3d.com>; Author <author@noreply.github.com>
Betreff: Re: [neherlab/covid19_scenarios] automatic bestfit of the past: automatic choose of all unknown parameter in such a way that the past is modelled in the best way, nearest to the already known data points (#290)

 

This is now integrated within the data pipeline. I'll close this, but if you have a more specific suggestion, please open another Issue!
