### ISSUE TITLE
Hospital Beds and ICU/ICMU - Regular Occupancy

### ISSUE THREAD

**Issue by cesarbrizio** [neherlab/covid19_scenarios#309]
First of all, I'd like to thank you guys for this magnificent work

The simulator doesn't take into account the Hospital Beds and ICU/ICMU beds that are already occupied by that time
And also consider that are no more regular hospitalizations caused by any other disease
Those numbers matters because when we are trying to figure out when the hospital infrastructure will be overwhelmed those others regular patients should be taken into consideration 

If we could add more inputs, we can solve this
1. How many Hospital Beds are already occupied?
2. How many ICU/ICMU are already occupied?
3. Regular patients admitted to Hospital Beds per day (Not by COVID19)

On severity assumptions
4. % of Regular patients transferred to ICU/ICMU (Critical - % of Regular admissions)
5. % of Regular patients deaths (Fatal - % of Regular critical patients)

Therefore, at the beginning of the simulation we can consider how many of the Hospital Beds and ICU/ICMU beds are already occupied and would still be occupied for the time that we had filled on the "Hospital stay" and "ICU stay" fields.
And we can continue to increase the number of hospitalizations considering the regular admissions to either Hospital Beds and ICU.

At the results, those regular patients that ended up death, should not be taken to the "Total Death" but to a different one
Let's say that a patient admitted to hospital > then to ICU > then dies, those numbers don't matter, but if a patient should have been admitted but couldn't because the hospital are already at his full occupancy, then those numbers matters, because the death rate will increase because of COVID19 patients.

So we must have a new result:
Regular Patients deaths [real - expected]: That result will consider how many of those patients should be admitted, gone to the ICU and died in regular conditions, and how many died because they couldn't have had access to hospital.

Example:
We have 1000 hospital beds and 200 ICU
700 hospital beds are already occupied
120 ICU are already occupied
30 regular patients are admitted per day
03 of them goes to ICU
01 of them dies

On a regular basis, that is, if all 30 regular patients have normal access to the hospital, then none of them matters
But as we increase the number of COVID19 patients hospitalized, and therefore we strangle the hospital capacity
Those 30 regular patients will not be admitted to the hospital, therefore, the percentage of severity overflow should also applied to them
So if 01 one them should die even if he had access to hospital, but instead 03 of them die because they couldn't had been hospitalized, them those extra 2 died because of the COVID19 crisis
That way, we can now show this statistic

**Comment by rneher** [comment]
Thanks for your thoughts. The hospital beds are currently not actually used in the simulation. But the ICU capacity does affect the outcome. This number should be thought of as ICU available for COVID19 patients. We are thinking about how to give this more realism, but we are hesitant to make the model more complicated and add more parameters. will need to think about this some more.

**Comment by rneher** [comment]
I currently don't see how we can provide these estimates at present. We have numbers for total available beds, but the user will have to adjust these if they have additional knowledge. Especially the time variable capacities introduce a large number of parameters that are difficult to make systematic.
