### ISSUE TITLE
No result calculated if Confirmed Cases = None 

### ISSUE THREAD

**Issue by ressel** [neherlab/covid19_scenarios#311]
Cool tool. Thanks a lot :thumbsup:

# 🐛 Bug Report
If input field "Confirmed cases" is set to "None", there is no result.

![Confirmed_Cases_None_Issue](https://user-images.githubusercontent.com/11699383/77944017-788bc500-72be-11ea-8de2-d700d0fb0cfd.JPG)

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser
 2. Set Confirmed cases to "None
 3. Run.

## 😯 Current Behavior
No reaction.  No diagram shown.  No change of the URL.

## 🤔 Expected Behavior
Result should be calculated, diagram should only show the simulation data.
URL should change to bookmarkable URL.

## 💁 Possible Solution
No idea.  It used to work, when real data was not present before.

## 🔦 Context
I am trying to do simulations with artificial data, like a population of 10, 100, 1000, 10000,
with no ICUs, ICUs equal to population etc.  Having to add Confirmed Cases disturbs and distorts the resulting diagrams.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |  Firefox, Chrome
| Operating System | Windows 10
|                  |

**Comment by rneher** [comment]
Yes, I also just ran into this.
