### ISSUE TITLE
ICUs = 0 does not plot data

### ISSUE THREAD

**Issue by ressel** [neherlab/covid19_scenarios#312]
Cool tool. Thank you! 👍 

# 🐛 Bug Report
If number of ICUs is set to zero, no data is plotted.

![ICU_Zero_Issue](https://user-images.githubusercontent.com/11699383/77946308-60b64000-72c2-11ea-9fbb-567eebd1a44b.JPG)

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser
 2. Set ICUs to 0.
 3. Run

## 😯 Current Behavior
Simulated data is calculated.
Data (both simulated and real) is **not** plotted.
Popup shows values for both simulated and real data.

If you switch to linear scale though, the missing data is plotted.

## 🤔 Expected Behavior
Data is plotted for log scale as well.

## 💁 Possible Solution
Potential root cause:
With log scale, the y value for 0 is undefined.  So grey horizontal line for ICU limit 0 cannot be drawn.
Solution: Do not draw line for ICU limit in this case.  It is not necessary anyway.

## 🔦 Context
I am playing around with some more or less artifical data, like being on an isolated island with no ICUs at all.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Firefox
| Operating System | Windows 10
|                  |

## Related
 - A change of Hospital Beds does not seem to have any effect on the simulation.  Is that expected?

**Comment by ivan-aksamentov** [comment]
Confirmed. Thanks for the report.
Just to clarify, are you trying to simulate a scenario where there are no ICU beds in the region?

**Comment by nnoll** [comment]
This is a log(0) bug. We should add a check if any bed number is set to 0 and just not show it if it is.

**Comment by ressel** [comment]
Yes, exactly.Thanks for your quick reply.Keep up the good work.
-------- Original message --------From: Ivan Aksamentov <notifications@github.com> Date: 3/30/20  20:56  (GMT+01:00) To: neherlab/covid19_scenarios <covid19_scenarios@noreply.github.com> Cc: ressel <ressel@gmail.com>, Author <author@noreply.github.com> Subject: Re: [neherlab/covid19_scenarios] ICUs = 0 does not plot data (#312) 
Confirmed. Thanks for the report.
Just to clarify, are you trying to simulate a scenario where there are no ICU beds in the region?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/neherlab/covid19_scenarios/issues/312#issuecomment-606179680",
"url": "https://github.com/neherlab/covid19_scenarios/issues/312#issuecomment-606179680",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ivan-aksamentov** [comment]
@ressel This was fixed in pull request #314  .
Might take some time to be released to live server, but here is an early testing version for this specific fix:
https://covid19-scenarios-git-fix-log-zero-plots.covid19-scenarios.now.sh/
