### ISSUE TITLE
Broken direct link to about page.

### ISSUE THREAD

**Issue by nnoll** [neherlab/covid19_scenarios#32]
Attempting to directly navigate to https://neherlab.org/covid19/about displays a page about a broken link.

**Comment by rneher** [comment]
this the result of our current hosting (non)-solution. 
https://neherlab.org/covid19/about
goes straight to cloudfront by-passing the app.

**Comment by ivan-aksamentov** [comment]
This should go away when we deploy to the root of a domain.
Don't want to spend time fixing the temp solution.

**Comment by ivan-aksamentov** [comment]
This is solved now that we've transitioned back to serving from the root.
