### ISSUE TITLE
Link not working and website /app crashes

### ISSUE THREAD

**Issue by nataliadgepi** [neherlab/covid19_scenarios#320]
# 🐛 Bug Report

Hello, 
I was changing the parameters to the model I created, when I changed the end date the website crashed and the webpage that states "Error! Oops something went wrong" popped up. I keep trying to refresh and reenter estimates but it crashes when I changed the end date.

Secondly, when I went to the 'about' page from the app page, the link was broken. At times, the mitigation line/dots are missing from the graph. 

Finally, it seems like the exponential curve of suspected cases doesn't really match confirmed cases anymore (i'm using a scaled down version), but amplitude is wide  and the peak is being estimated for a month later than most other models and they are all using the same Ro of 2.3, just wondering why?

Thank you !
Natalia

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser
 2.
 3.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System |
|                  |

## Related

 -

**Comment by ivan-aksamentov** [comment]
Hi Natalia @nataliadgepi,

Thanks for the report!
It seems that you are having 3 separate issues (or even more), so let's consider them separately.

> I was changing the parameters to the model I created, when I changed the end date the website crashed and the webpage that states "Error! Oops something went wrong" popped up. I keep trying to refresh and reenter estimates but it crashes when I changed the end date.


I think it may be that we just forgot to handle a particular case and these parameters got saved to the URL. So now every time you try this URL, the app restores the faulty params and things go bad again.

> when I went to the 'about' page from the app page, the link was broken

This sound like the same issue as reported here: ttps://github.com/neherlab/covid19_scenarios/issues/32 and here https://github.com/neherlab/covid19_scenarios/issues/250 .
We fixed this in our latest version but it is not on live server yet. It will be soon.

Let me know if it is not the same issue. Then we will have to investigate!

> At times, the mitigation line/dots are missing from the graph.

We are currently working on replacing the mitigation UI. See issue: https://github.com/neherlab/covid19_scenarios/issues/14 . Hopefully that should solve the problems and inconveniences of the current implementation.

>  it seems like the exponential curve of suspected cases doesn't really match confirmed cases anymore (i'm using a scaled down version), but amplitude is wide and the peak is being estimated for a month later than most other models and they are all using the same Ro of 2.3, just wondering why?

I will let @nnoll and @rneher to address the science


Overall, there is probably a set of parameters that leads to an error you encountered and there is absolutely no way I can just go and guess these particular parameters. There are too many combinations. It is very important that you help us to reproduce the problem(s) by providing step-by-step instructions  we asked in "How to reproduce" section.

Additionally, could you please check if you can reproduce any of these issues on this version of the app:
https://staging.covid19-scenarios.org/
(this is the address where you can find the app version that has all the latest fixes and features, but that we haven't yet published on the main website yet)

**Comment by nataliadgepi** [comment]
Thank you for your quick reply and all your hard work. The model is working well now and the links work. I've modified latency and infectious period to get the curve that matches the data for now (although I'd rather have it fit to the expected values).

**Comment by nnoll** [comment]
@nataliadgepi would you mind sharing what region/scenario you are simulating? Our data fitting has been overhauled to a more robust solution that should be live soon (next day or two). So this should fix your issue but I'm curious to test your issue on my end.

**Comment by nataliadgepi** [comment]
@nnoll <https://github.com/nnoll>  Thank you for your response. I'm
specifically looking at data in a local hospital in Ontario. these are the
parameters that I'm using but they don't seem to match the exponential
curve of confirmed cases seen in Ontario and estimated peak dates in other
models (peak used to be mid april which is similar to other epi models
performed here in Canada (e.g. by d fisman) ).

I'm interested in forecasting for a single hospital so I've run a baseline
scenario for Ontario (using Ontario data) and the hospital using the
following parameters for epidemiology:

*Ontario scenario:*
Initial suspected cases = 2100
Imports per day = 10
Confirmed cases = CAN - Ontario
Time range: March 15 to Aug 31

*Epidemiology:*
Ro = 2.3
Latency = 5
Infectious period = 3
Seasonal forcing  = 0.1
seasonal peak = january
Hospital stay = 7
ICU stay = 10
Severity of ICU overflow = 2

Severity assumptions --> using proportions from Verity et al
<https://www.thelancet.com/journals/laninf/article/PIIS1473-3099(20)30243-7/fulltext>
and
Ferguson NM et al
<https://sciencebusiness.net/sites/default/files/inline-files/Imperial-College-COVID19-NPI-modelling-16-03-2020.pdf>


I start w a weak mitigation, then moderate then strong, then I modify it
manually to see how it matches gov't interventions.

Thank you!

**Comment by rneher** [comment]
The original issue with subpages should be addressed now. Closing this.
