### ISSUE TITLE
poor countries / high inequality: no beds, near starvation

### ISSUE THREAD

**Issue by hmijail** [neherlab/covid19_scenarios#335]
Some countries have a lot of population who once they get sick will have little chance to get an hospital bed, much less ICU. Also for them isolation won't be helpful or even possible: no savings, living day to day, cramped quarters, no sanitation. They need to work every day to eat.

Still, some such countries are implementing forced isolation. 

This kind of scenario doesn't seem simulable currently. Maybe it'd be enough to do something like "average days until starvation"? (no idea what to do after those days: death?)

**Comment by noleti** [comment]
I will to close, as the purpose of this project is to

> explore the dynamics of COVID19 cases and the associated strain on the health care system in the near future

Accurate economical (and psychological, political, environmental, etc) effect simulation of mitigations measures (to show trade-offs) are out of scope in my opinion.
