### ISSUE TITLE
Equation error in https://neherlab.org/covid19/about

### ISSUE THREAD

**Issue by MarcelloPerathoner** [neherlab/covid19_scenarios#34]
Not sure if this is the right place to report but on https://neherlab.org/covid19/about the differential equation for ```dRa(t) / dt``` should end with ```(1 - ca) Ha(t) / th```.

**Comment by ivan-aksamentov** [comment]
@MarcelloPerathoner thanks for the report!
@rneher and @nnoll will investigate it soon.

**Comment by rneher** [comment]
Thanks, should be fixed in 18e277563944ca8f7deef255b9f117143031357a. Will up with the next deploy.
