### ISSUE TITLE
Fit deaths instead of infected

### ISSUE THREAD

**Issue by fabiansvara** [neherlab/covid19_scenarios#340]
It seems you are fitting to the number infected; this could lead to misleading results that are also very poorly comparable between different countries. It might be useful to fit to deaths instead, as in Flaxman et al. [1]. This method also yields considerably higher R_0 values than in the simulator defaults.

[1] http://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-Europe-estimates-and-NPI-impact-30-03-2020.pdf

**Comment by nnoll** [comment]
@fabiansvara. In the new scheme we fit to both, while also fitting the testing %, or the fraction of cases actually captured by the testing infrastructure of a given country. I would also caution against trusting cumulative fatalities as a zero-noise column. While there is reason to believe you capture the extreme cases more accurately, there is evidence that shows that death counts suffer from underreporting, e.g. Bergamo Italy as they are ultimately subject to the same testing limitations.
