### ISSUE TITLE
Improved dependency management

### ISSUE THREAD

**Issue by tryggvigy** [neherlab/covid19_scenarios#342]
- As a contributor I would like to quickly install the required dependencies to start working after cloning.
- As a maintainer I would like have explicitly declared, version frozen dependencies that I can audit for security issues.

I don't use python often. When I cloned the project and tried to generate date for the first time, I saw I had missing dependencies. I set up https://github.com/pypa/pipenv, which seems to be the tool of choice in the python ecosystem nowadays, and installing the missing dependencies.

I believe managing dependencies with `pipenv` could lower the barrier to contribution.

**Comment by nnoll** [comment]
I usually keep everything within one pipenv because I'm lazy, but I do think it's good to be explicit about dependencies, especially if one wants to pull from the head of a repo. I've made a pipenv file that should allow one to just type pipenv install inside the data directory to accomplish this.

**Comment by tryggvigy** [comment]
Thanks for considering. I think this is an improvement for new folks coming in to contribute. Especially those that do not work in python on a regular basis like myself
