### ISSUE TITLE
Improve interaction with the app

### ISSUE THREAD

**Issue by rneher** [neherlab/covid19_scenarios#343]
The primary purpose of this repo is to aggregate parsers and sources to be used in [`covid19_scenarios`](https://github.com/neherlab/covid19_scenarios) where it is included as a submodule. 

In PR https://github.com/neherlab/covid19_scenarios/pull/267 automated updating of the app is discussed and one issue is robustness. Suggestions are

  * separate parsing and tsv generations from json generation. tsv can be manually checked, committed and then jsons are generated from there. potentially change folder structure to be flat. 
  * make json generation more robust.

**Comment by noleti** [comment]
The .json validation is being addressed now in https://github.com/neherlab/covid19_scenarios/pull/390. In general, this is related to https://github.com/neherlab/covid19_scenarios/issues/283 (references to keep things synchronized).

**Comment by ivan-aksamentov** [comment]
This was mostly done in #390 and #434
