### ISSUE TITLE
Keep track of sources for populationData.tsv

### ISSUE THREAD

**Issue by nnoll** [neherlab/covid19_scenarios#348]
As of now we don't track where we get this data from. I propose we amend sources.json to have two top-level fields: ["case-counts", "populationData"] in which we store all information from which we derive our data. 

The data below "case-counts" would be equivalent to what's now, while "populationData" would hold analogous level information for hospital bed/ICU capacity. Keys in the JSON should be equivalent to the country name.

**Comment by noleti** [comment]
@nnoll I will start working on this over this weekend. Any updates wrt latest changes?
