### ISSUE TITLE
🇪🇸 Add Spanish regions

### ISSUE THREAD

**Issue by rneher** [neherlab/covid19_scenarios#349]
To use Spanish regions as preset populations, we need their population sizes and some estimates of the number of cases they had on March 1st (today/200 is probably not too bad)

@mserranom, do you have those numbers?

They would need to go into the `populationData.tsv` in analogy to the Italian provinces:

https://github.com/neherlab/covid19_scenarios_data/blob/master/populationData.tsv#L76

**Comment by nnoll** [comment]
I'm going to close this as I think it's gone stale. Please reopen a new issue if someone wants to discuss or anything moves here.
