### ISSUE TITLE
Why when I increase the "infectous period" it flatters the curve?  

### ISSUE THREAD

**Issue by Adriano-Pinter** [neherlab/covid19_scenarios#35]

**Comment by Adriano-Pinter** [comment]
Why when I increase the "infectous period" it flatters the curve?

**Comment by rneher** [comment]
Increasing the infectious period at fixed R0 implies that the infectious cycle is slower, flattening the curve. This might be unintuitive but is expected.

**Comment by Adriano-Pinter** [comment]
This is really unintuitive....     I guess in real life if a infectous period is larger the R0 increases...  I ll try to play with both indicators, instead only with Infectous period.

**Comment by Adriano-Pinter** [comment]
Thanks!
