### ISSUE TITLE
iPad (horizontal orientation): no button for entering the app

### ISSUE THREAD

**Issue by dkozar** [neherlab/covid19_scenarios#356]
# 🐛 Bug Report

When website opened for the first time in iPad, the user cannot pass the home screen since there’s no button (in horizontal orientation).

The button is there if one rotates the iPad to vertical orientation.

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser on iPad (Safari, Chrome...)
 2. There is no button to dismiss the home screen

![iPad](https://user-images.githubusercontent.com/1078403/78661621-ffe0c600-78c6-11ea-9e74-b6860eb0abf7.jpg)

**Comment by ivan-aksamentov** [comment]
Landing page will be removed soon
