### ISSUE TITLE
reloading url resets parameters when running locally

### ISSUE THREAD

**Issue by jc92** [neherlab/covid19_scenarios#362]
# 🐛 Bug Report

When running yarn prod:watch and running the simulator locally.
- Population and epidemic parameters revert to default parameters after reloading.
- Mitigation curve resets whenever a new location is set
## How to reproduce
1. run simulator locally
2. change some parameters
3. run simulator
4. reload

## 😯 Current Behavior

Same as above
When running yarn prod:watch and running the simulator locally.
Population and epidemic parameters revert to default parameters after reloading

## 🤔 Expected Behavior

I thought the local version would work as the one currently from the website, where when reloading maintains current settings.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Chrome
| Operating System | MacOS
|                  |

## Related

 -

**Comment by jsmith** [comment]
Due to recent change some parameters are not serialized. This is fixed in #329 I think!
