### ISSUE TITLE
Query string doesn't persist through landing page. 

### ISSUE THREAD

**Issue by rneher** [neherlab/covid19_scenarios#370]
# 🐛 Bug Report
The app provides shareable links. But for me the query string is lost when transitioning through the landing page, rendering the entire URL serialization pointless. We have a couple of great PRs that all use query strings.

## How to reproduce
open 
https://staging.covid19-scenarios.org/?%7B%22population%22%3A%7B%22ICUBeds%22%3A1755%2C%22cases%22%3A%22Belgium%22%2C%22country%22%3A%22Belgium%22%2C%22hospitalBeds%22%3A63692%2C%22importsPerDay%22%3A1%2C%22populationServed%22%3A11590000%2C%22suspectedCasesToday%22%3A1%7D%2C%22epidemiological%22%3A%7B%22infectiousPeriod%22%3A4%2C%22latencyTime%22%3A3%2C%22lengthHospitalStay%22%3A4%2C%22lengthICUStay%22%3A14%2C%22overflowSeverity%22%3A2%2C%22peakMonth%22%3A0%2C%22r0%22%3A4.1%2C%22seasonalForcing%22%3A0.2%7D%2C%22simulation%22%3A%7B%22simulationTimeRange%22%3A%7B%22tMin%22%3A%222020-02-13T00%3A00%3A00.000Z%22%2C%22tMax%22%3A%222020-09-01T00%3A00%3A00.000Z%22%7D%2C%22numberStochasticRuns%22%3A0%7D%2C%22containment%22%3A%5B%7B%22t%22%3A%222020-02-13T00%3A00%3A00.000Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-02-27T08%3A34%3A17.142Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-03-12T17%3A08%3A34.285Z%22%2C%22y%22%3A1%7D%2C%7B%22t%22%3A%222020-03-27T01%3A42%3A51.428Z%22%2C%22y%22%3A0.41666666666666663%7D%2C%7B%22t%22%3A%222020-04-10T10%3A17%3A08.571Z%22%2C%22y%22%3A0.41666666666666663%7D%2C%7B%22t%22%3A%222020-04-24T18%3A51%3A25.714Z%22%2C%22y%22%3A0.41666666666666663%7D%2C%7B%22t%22%3A%222020-05-09T03%3A25%3A42.857Z%22%2C%22y%22%3A0.41666666666666663%7D%2C%7B%22t%22%3A%222020-05-23T12%3A00%3A00.000Z%22%2C%22y%22%3A0.41666666666666663%7D%2C%7B%22t%22%3A%222020-06-06T20%3A34%3A17.142Z%22%2C%22y%22%3A0.41666666666666663%7D%2C%7B%22t%22%3A%222020-06-21T05%3A08%3A34.285Z%22%2C%22y%22%3A0.41666666666666663%7D%2C%7B%22t%22%3A%222020-07-05T13%3A42%3A51.428Z%22%2C%22y%22%3A0.41666666666666663%7D%2C%7B%22t%22%3A%222020-07-19T22%3A17%3A08.571Z%22%2C%22y%22%3A0.41666666666666663%7D%2C%7B%22t%22%3A%222020-08-03T06%3A51%3A25.714Z%22%2C%22y%22%3A0.41666666666666663%7D%2C%7B%22t%22%3A%222020-08-17T15%3A25%3A42.857Z%22%2C%22y%22%3A0.41666666666666663%7D%2C%7B%22t%22%3A%222020-09-01T00%3A00%3A00.000Z%22%2C%22y%22%3A0.41666666666666663%7D%5D%2C%22current%22%3A%22Custom%22%7D

after the landing page the page loads with default parameters. 

## 🤔 Expected Behavior
The page should load the custom parameters. 

## 🌍 Your Environment

Firefox 74, Ubuntu 16.04

## Related
#293 #329 #366

**Comment by dkozar** [comment]
FYI Speaking of a landing page, there is a TINY LITTLE CHECKBOX at the bottom of the page:

![image](https://user-images.githubusercontent.com/1078403/78298156-2f8b7900-7529-11ea-8788-d8622bd381ce.png)

... this checkbox should really be bigger, because nobody sees it. Once checked, this is saved to local storage (for the domain) and landing page is not bugging you again:

![image](https://user-images.githubusercontent.com/1078403/78298523-5e561f00-752a-11ea-97d8-76bbb311478a.png)

So, if you for some reason already checked this checkbox, and would like to bring the homepaga again, you got to go to local storage and clear this record.

**Comment by gj262** [comment]
this can be fixed by adding state to the <Redirect /> in <App /> and using it on the <Link /> in <LandingPage />

**Comment by dkozar** [comment]
OK, taking a look!

**Comment by dkozar** [comment]
@rneher there you go: https://github.com/neherlab/covid19_scenarios/pull/372

Thanks @gj262! :)

**Comment by dkozar** [comment]
![landing-page-query-string](https://user-images.githubusercontent.com/1078403/78304339-67e58400-7536-11ea-902a-725956e6ab2b.gif)

Video: https://microsofteur-my.sharepoint.com/:v:/g/personal/dakozar_microsoft_com/EY9-L0XI1BJLkxj_Y9QED78BCYcyvehkvgIvOW5EvGmBjg?e=Rph0Sn

**Comment by dkozar** [comment]
PR merged, the issue could now be closed.
