### ISSUE TITLE
Model Review - Feature request variable numbers of ICU beds

### ISSUE THREAD

**Issue by gavinpotter** [neherlab/covid19_scenarios#379]
# 🙋 Feature Request

To be able to enter a varying (by time) number of ICU beds.

To enable the user to input predicted numbers of ICU beds

## 🔦 Context

There are two main policy responses that governments are implementing in response to the virus:  The first is some form of social distancing / lock down procedures and your model covers those nicely.

The second policy response is to increase the number of ICU beds.  As far as I can tell, you can only enter a fixed number of ICU beds.  

To enable governments to explore alternative policy decisions it would be good if they could also enter the number of ICU beds over time.  I have read aeon-lakes comment that its a 'nice to have', but significant resources are being allocated to this and it would be useful to be able to understand whether more resources should be dedicated to this or, say, increasing the restrictiveness of the lockdown procedures.

## 😯 Describe the feature

I think the easiest way to enter the data would be a table where the user entered a number of ICU beds at the end of the week.  - The model could assume a straight line increase between the previous week's figure and this weeks figure when calculating the number of ICU beds available.

**Comment by rneher** [comment]
This could be an interesting addition. 
We could add a specific measure similar to the mitigation intervals that don't reduce r0 but increase the number of ICU beds. The number of ICU beds are only relevant once that demand exceeds that number. One first workaround is to simply enter the maximal number of ICU beds.

**Comment by nnoll** [comment]
Hey Gavin, thanks for the suggestion. For now I think we will close this issue as I don't think any of us will get to implement this and I think adding another table for this feature would incommensurately increase complexity relative to benefit gained. But feel free to open another issue if this problem is still pertinent.
