### ISSUE TITLE
[IMPORTANT] Fix delay when adding mitigation intervals

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#382]
# 🐛 Bug Report

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser
 2. Click "Add" button in "Mitigation"
 3. Observe that it takes a while for the new interval to appear in the table

## 😯 Current Behavior

New intervals appear after delay

## 🤔 Expected Behavior

New intervals should appear instantly

## 🔦 Context

It's either "Add" button is wrongly debounced or it waits for the algorithm to finish, or both.

Importance:  Intervals is a commonly asked for feature. Should be included into the next release.

## 🌍 Your Environment

Any

## Related

 - https://github.com/neherlab/covid19_scenarios/pull/323
 - https://github.com/neherlab/covid19_scenarios/issues/14

**Comment by abrie** [comment]
There are two debounced callbacks in `Main.tsx`:

One to auto-run the simulation: https://github.com/neherlab/covid19_scenarios/blob/af9377ee3799bee646279d1f77b36abef9a69a05/src/components/Main/Main.tsx#L123-L127

And another for the scenario state: https://github.com/neherlab/covid19_scenarios/blob/af9377ee3799bee646279d1f77b36abef9a69a05/src/components/Main/Main.tsx#L143-L161

Debouncing the auto-run makes sense. But why is the scenario state being debounced too?

**Comment by gj262** [comment]
Hi @abrie, the debounce on setScenarioToCustom (triggered by form validation) is there because user interactions with the form cause `<Main />` re-renders for every interaction. That is OK when it is just the form. But when the results graphs are present the UI is un-useable.

**Comment by gj262** [comment]
But @abrie I should have added that you are probably right in that that is where the delay is introduced. 

MitigationTable adds the new row to scenarioState using that Formik validation method.

**Comment by gj262** [comment]
Because changes to how `<Main />` handles changes to the form are tricky, and not likely to happen any time soon, I'd opt for a clean(ish) workaround. Something like add some state to `<MitigationTable \>` that optimistically adds to an optimisticMitigationIntervals array and displays them (readonly) along with the others. Once the incoming prop catches up they could be removed. 

Corner case: If the addition is rejected by `<Main />`, `<MitigationTable \>` would not notice. It should time limit its optimism 😆

**Comment by abrie** [comment]
@gj262 Looks like the DeterministicLinePlot is at fault!

**Comment by ivan-aksamentov** [comment]
Improved in #437 
Open new issues/ PR for folowup
