### ISSUE TITLE
[IMPORTANT] Fix styling of mitigation intervals

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#383]
# 🐛 Bug Report

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser
 2. Observe "Mitigation" section. 

## 😯 Current Behavior

Intervals are not properly aligned. The sizes of input fields should be adjusted for the sizes of their common contents: name is much longer than the strength number.
Test on various screen sizes.

## 🤔 Expected Behavior

Should be pretty :woman_artist: :sparkles:  

## 🔦 Context

Importance:  Intervals is a commonly asked for feature. Should be included into the next release.

## 🌍 Your Environment

Any

## Related

 - https://github.com/neherlab/covid19_scenarios/pull/323
 - https://github.com/neherlab/covid19_scenarios/issues/14

**Comment by kmid5280** [comment]
@ivan-aksamentov Are you saying that the inputs should match the width of their contents? I.e. the name input should be longer, whereas the number input should be shorter? Are you also wanting changes to the spacing or positioning of the buttons (do you want them stacked on top of each other)? What about the trash can button placement?

![mitigation](https://user-images.githubusercontent.com/35879775/78458935-7d5fc880-7672-11ea-86ef-d656ff47d4e0.png)

**Comment by dkozar** [comment]
I think that (on the mobile) we should use the same widths as for existing elements above and below the mitigation intervals:

![image](https://user-images.githubusercontent.com/1078403/78510625-8e9df780-778e-11ea-8fe4-6523ba1ff567.png)

As you can see, all the controls have full width except buttons. Buttons have text.

I personally like buttons that have both the icon and text:

![image](https://user-images.githubusercontent.com/1078403/78510693-269be100-778f-11ea-9199-8b488b35fa7f.png)

**Comment by dkozar** [comment]
As for desktops, first control should probably auto-stretch (flex: 1), green arrow here:

![image](https://user-images.githubusercontent.com/1078403/78510749-872b1e00-778f-11ea-8dbb-68bbac43b3c3.png)

In the above screenshot, I've put all the row padding to `4px`, and margin-right for each control (except last) to `4px`. I've put width: `70px` to numeric stepper (red arrow) to get some more width (not sure how big the numbers are and how many decimals are there). The calendar control's height should be set to be the same as other controls in the row.

Of course, let's ask the UX experts to take a look and suggest,
