### ISSUE TITLE
Replacing the scenario dropdown with "Load scenario" dialog

### ISSUE THREAD

**Issue by dkozar** [neherlab/covid19_scenarios#397]
# 🙋 Feature Request

Let's replace this dropdown with a "Load scenario" button:

![image](https://user-images.githubusercontent.com/1078403/78424166-71203f00-7663-11ea-8571-1b1a964db4fb.png)

## 🔦 Context

There is a general confusion about what this dropdown means and how does it relate to parameters, once the parameters are changed.

Also, there's no clear vision on **should we serialize this parameter** to query string in the URL.

My conclusion is that this actually isn't one of the input parameters. It's just a way of loading an existing scenario. So, let's remove the dropdown because this is not a parameter.

If we need to have a scenario name on top of the page (for sharing purposes etc.), then we can have a text field with scenario name and text area for description.

## 💁 Possible Solution

Button:

![image](https://user-images.githubusercontent.com/1078403/78424199-a2007400-7663-11ea-9b21-050570edc221.png)

Dialog:

![load-scenario-2](https://user-images.githubusercontent.com/1078403/78424205-a9c01880-7663-11ea-9f2f-83918500d2bf.png)

This would make a "scenario picker" a rich control, providing much more context (author, description etc.), which is great as the number of scenarios grows.

There would also be a "Search" field on top, and possibly some user filters, pagination etc. There could be a filter for seeing only "My scenarios", or the ones belonging to "My org".

**Comment by rneher** [comment]
I agree, this is more intuitive. these scenarios are really just presets that can be tweaked. I like the proposal.

**Comment by dkozar** [comment]
Let's engage the UX and implement it. It should be pretty simple.

**Comment by nnoll** [comment]
I just saw this after the opened PR. I really like this direction, particularly the potential flexibility with loading presets or even as a way to distribute narratives. The scenario name is ultimately not a parameter but rather a way for people to get to the simulation they care about. This could honestly go on the now deprecated landing page...

Also regarding serializing the scenario name, we should not serialize this. It is ultimately not a parameter as you stated.

**Comment by dkozar** [comment]
Yeah, the dropdown is really confusing, even to us contributors ("is it one of the params or not?").

It's the first usability issue the user encounters in the app; let's fix it.

**Comment by ivan-aksamentov** [comment]
Resolved in #490
