### ISSUE TITLE
What's the meaning of Imports per Day?

### ISSUE THREAD

**Issue by WalkerWalker** [neherlab/covid19_scenarios#4]
Thanks for the model and the simulation. That's amazing. 

Some explanation would be nice for non-research folks.  For example, What's the meaning of Imports per Day? Thanks!

**Comment by rneher** [comment]
Thanks for the suggestion! 
We now have little explanation buttons for each field. I hope this addresses the issue.

**Comment by WalkerWalker** [comment]
absolutely Thansk!
