### ISSUE TITLE
Glitch, webpage gets stuck when severity table (fatal column) is updated

### ISSUE THREAD

**Issue by nataliadgepi** [neherlab/covid19_scenarios#413]
# 🐛 Bug Report

When I update the severity table with proportions based on national data, the webpage/model gets stuck and doesn't allow me to scroll down to see the model. It happens particularly when I update the proportions in the fatal, % critical column.

## How to reproduce
update severity, in particular the last two 'fatal, %critical' cells and the webpage will get stuck.
Steps to reproduce the issue:

 1. Open the application in a browser
 2.update severity, in particular the last two 'fatal, %critical' cells and the webpage will get stuck, you cannot scroll down to see the model, run it or export it.
 3.

## 🌍 Your Environment

Mac OS, Chrome browser.

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System |
|                  |

## Related

 -

**Comment by rneher** [comment]
thanks for raising this, @nataliadgepi. but I am not reproducing this on linux firefox or chrome. Are you referring to current master or neherlab.org/covid19 ?

**Comment by nataliadgepi** [comment]
@rneher Thank you for the message. It seems to be fixed now. Not sure what it was.
