### ISSUE TITLE
Global data

### ISSUE THREAD

**Issue by keithloise** [neherlab/covid19_scenarios#42]
Commended for great work!

Wondering if you have a global data of this?

**Comment by nnoll** [comment]
Can you clarify your question a bit. Are you asking do we have global case-counts, hospital beds, and simulate the global population at once?

**Comment by keithloise** [comment]
> Can you clarify your question a bit. Are you asking do we have global case-counts, hospital beds, and simulate the global population at once?

Your population selector by countries are limited to EU only. If you could add other countries too that would be great.

**Comment by nnoll** [comment]
All country age distributions should be able to be found in the dropdown menu within the Population data card. We however don't have data on hospital bed or ICU capacity for all countries at this time, but are activately working on aggregating this. If you have access to this data for your country/region of interest, head over the the covid19_scenarios_data repo and add this data to the populationData.tsv! 

I'll close this here but invite you to open a more specific issue and/or pull request on the other repo. Thanks
