### ISSUE TITLE
[IMPORTANT] Ajv breaks production build

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#430]
# 🐛 Bug Report

## How to reproduce

Steps to reproduce the issue:

 1. `yarn prod:watch`
 2. Open the application in a browser
 3. Notice Error page and  console errors

## 😯 Current Behavior

Errors

## 🤔 Expected Behavior

No errors

## 🔦 Context

Ajv compiles schemas on app startup and is using unsafe eval-like `Function` constructor. This is blocked by our Content Security Policy.

## 💁 Possible Solution

There are tools that allow to precompile Ajv's validator functions at build-time, so there is no eval. I would like someone to try this.

For example, take a look at 
https://github.com/gajus/table/blob/db1ad68d74b8e859448deebaeb823da39e40fa98/package.json#L76-L83

## Related

 - #390

**Comment by kmid5280** [comment]
@ivan-aksamentov I'm not sure that this is related to Ajv per se, I think that imports are not being handled correctly in tools/convertSchemasToType.ts. When I run 'yarn dev' it gives me a 'SyntaxError: Unexpected identifier' error and points to the Ajv import in tools/convertSchemasToType.ts. If you move or remove that import, it will display the same error but with the next import in the list (in this case, rimraf).

**Comment by ivan-aksamentov** [comment]
Was fixed in https://github.com/neherlab/covid19_scenarios/pull/434
