### ISSUE TITLE
Default time range of simulation should be ETA of vaccine

### ISSUE THREAD

**Issue by MarcelloPerathoner** [neherlab/covid19_scenarios#44]
~18 month is the ETA of the vaccine. That seems like the most natural time range to simulate.

**Comment by ivan-aksamentov** [comment]
@MarcelloPerathoner 
Hi Marcello,

Yes it might be a reasonable default if you want to predict the grand totals towards the end of the pandemic.

However the most "interesting" part of the outbreak will be unrolling in the coming weeks to months and we want to put emphasis on how mitigation/containment measures influence the numbers around the peak. Also, showing longer intervals make plots quite crammed (which is a user interface/design problem).

We may change the defaults as situation evolves and as we introduce user interface improvements.

Meanwhile,  you can always adjust the time range in "Simulation time range" parameter.

**Comment by MarcelloPerathoner** [comment]
This paper https://www.imperial.ac.uk/media/imperial-college/medicine/sph/ide/gida-fellowships/Imperial-College-COVID19-NPI-modelling-16-03-2020.pdf suggests that a too strong suppression in the first 5 months will cause the peak to appear in December. Your default timescale will completely miss this point. See Figure 3.

**Comment by ivan-aksamentov** [comment]
@MarcelloPerathoner Thanks for the suggestions!
I'll let our science forks to consider this.
CC @nnoll @rneher

**Comment by nnoll** [comment]
For now, we want the model to focus on understanding the immediate hospital demand in the next 3-6 months, and the various control we have on it. Increasing the default time-range blurs this focus, as well as introduces worries of uncertainty in predictions looking that far forward in time, which our model has no way of calculating and/or displaying right now. 

For now, I think we'll opt to leave it at 6 months, however the simulation time range can be edited for you to explore longer scenarios. Thank you for your suggestion -- it's certainly a good point and something we can revisit later down the road as the model improves. So I'll close this for now but feel free to re-open later!
