### ISSUE TITLE
Spinner is not centered

### ISSUE THREAD

**Issue by dkozar** [neherlab/covid19_scenarios#442]
## 😯 Current Behavior

![spinner](https://user-images.githubusercontent.com/1078403/78603779-9d4ce300-7850-11ea-897a-a6f14126a815.png)

## 🤔 Expected Behavior

![spinner2](https://user-images.githubusercontent.com/1078403/78603797-a2aa2d80-7850-11ea-9609-f1c377662308.png)

**Comment by gj262** [comment]
Improved by @kmid5280 🎉.
Still not quite centered though.
