### ISSUE TITLE
Allow for fine-grained values in numeric inputs while also preserving step size

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#443]
# 🐛 Bug Report

Some numeric boxes:
 - have step size defined (a value by which value will be incremented/decremented when clicling arrows)
 - allow for finer values to be valid

For example, for the mitigation strength, we want arrows to increment by 0.1, but we allow values like 0.48 too. Currently this does not work, you can have either one or another:

![Screenshot from 2020-04-06 22-46-51](https://user-images.githubusercontent.com/9403403/78603936-40a1f600-7859-11ea-95db-9960a538b87a.png)

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser
 2. Increment-decrement mitigation strength at will
 3. Try to input 0.48, observe the built--in browser validation error

Note, this issue is applied to all of the numeric fields, not only mitigation strength.

## 😯 Current Behavior

Fine-grained values are not accepted

## 🤔 Expected Behavior

Both, step and fin-grained values work

## 💁 Possible Solution

This is related to the validation attributes in `<input />` tags

There are many libraries exist for numeric inputs, however we would prefer a solution that:
 - has all the features that are currently present
 - uses `<input />`
 - looks native for the browser and platform
 - allows for keyboard navigation (e.g. tab focus)
 - accessible for screen readers (not a "build everything from divs" or at least with aria attributes)
 - accessible for navigation
 - can be internationalized

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System |
|                  |

## Related

 -

**Comment by abrie** [comment]
Putting this here for possible relevance:

https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/

**Comment by abrie** [comment]
Component candidate:
https://react-component.github.io/input-number/examples/decimal.html

**Comment by abrie** [comment]
@ivan-aksamentov I'm no longer able to replicate this behavior on master (OSX: Chrome, Firefox, Safari). Could you please confirm?

**Comment by ivan-aksamentov** [comment]
@abrie 
![Screenshot from 2020-04-12 22-46-35](https://user-images.githubusercontent.com/9403403/79079461-85bda080-7d0f-11ea-8bb3-e3eab816376e.png)

We made it less relevant by multiplying the values by 100, but it's still there.
Might still be relevant for other fields, maybe we just haven't noticed.

This issue is definitely less of a priority right now compared to what it used to be with decimals.

**Comment by abrie** [comment]
@ivan-aksamentov. I'm at a loss – still unable to replicate this. Your screenshot shows a puzzling validation message: 41.56 is not acceptable, but 41.55 and 42.55 are? For a step of 1?

Screencap of behavior I see:
![novalidation](https://user-images.githubusercontent.com/1462268/79079987-56436f80-7ce0-11ea-9c8e-811cd0a9c9b4.gif)

**Comment by ivan-aksamentov** [comment]
@abrie The popup appears if you hit Enter for sure, but I think in some other cases too. It seems to be hard to repro and might differ between browsers.

I think I found a solution, at least partial:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-novalidate

Not sure the update is still happening properly in all the cases, but I am making a hotfix for that on release.

**Comment by abrie** [comment]
Yeah, discovered the same: See PR #531

**Comment by ivan-aksamentov** [comment]
This was mostly resolved in #534
