### ISSUE TITLE
[UX] Issues on mobile

### ISSUE THREAD

**Issue by dkozar** [neherlab/covid19_scenarios#444]
# 🐛 Bug Report

Here's how the app looks like on iPhone 6. The diclaimer seems to get clipped by screen edges.

![img1](https://user-images.githubusercontent.com/1078403/78604295-81960c80-7851-11ea-8bb9-2b403da4f8a0.png)

![img2](https://user-images.githubusercontent.com/1078403/78604296-82c73980-7851-11ea-8050-db46282a3de7.png)

![img3](https://user-images.githubusercontent.com/1078403/78604297-82c73980-7851-11ea-98e4-173efe262227.png)

**Comment by ivan-aksamentov** [comment]
Related to #71

**Comment by ivan-aksamentov** [comment]
Landing page will be removed soon.
