### ISSUE TITLE
Autorun won't run on first attempt

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#448]
# 🐛 Bug Report

On fresh start, checking "autrun"  does not trigger a run.

## How to reproduce

Steps to reproduce the issue:

 0. Clear local storage
 1. Open the application in a browser
 2. Check "autorun" checkbox. Notice that no run is triggered.
 3. "Run" button is disabled - impossible to trigger manually. 

Application reaches an invalid state and it is not intuitive.

## 😯 Current Behavior

On fresh start, checking "autrun"  does not trigger a run.

## 🤔 Expected Behavior

On fresh start, checking "autrun"  triggers a run.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System |
|                  |

## Related

 -

**Comment by dkozar** [comment]
Isn't the point of autorun to run on parameters change?

And also, the point of this checkbox is switch autorun on and off, not to actually **run**, no? To me this looks fine like this. What do you think?

**Comment by dkozar** [comment]
![BB88727D-4B55-48B1-A619-646701015590](https://user-images.githubusercontent.com/1078403/78611301-8ca36980-785e-11ea-8174-e2482375f18a.GIF)

**Comment by noleti** [comment]
How about just triggering one run after the box is checked? This would solve the problem with minimal overhead, no?

**Comment by ivan-aksamentov** [comment]
@dkozar 
 1. This is how it worked previously. I don't see any reason to change.
 2. What if user wants to run with these exact parameters AND with autorun from now on?
 3. It's confusing for first visitors who enable autorun first and will see that nothing happens and the Run button is disabled => WTF => close the tab => client lost

@noleti That would be a simple patch. But I think we have enough patches already. This may also be an indicator of a much serious problem with either side effect handling or debouncing logic, so I'd like someone to have a quick look at the bigger picture.

We should have more unit and e2e tests to avoid this kind of anti-features creeping in.

**Comment by dkozar** [comment]
> 3\. It's confusing for first visitors who enable autorun first and will see that nothing happens and the Run button is disabled => WTF => close the tab => client lost

That is true. Why are we disabling the button anyway? I think both the button and autorun might co-exist.

> 1\. This is how it worked previously. I don't see any reason to change.

Back then I was finding it confusing. Because the checkbox says: _"Autorun Simulation on scenario parameter change"_ and **not** _"Autorun Simulation on scenario parameter change and also now"_ 😄 
I guess my problem is that I'm taking things literally.
