### ISSUE TITLE
Getting SyntaxError: Unexpected identifier error when attempting to start application

### ISSUE THREAD

**Issue by kmid5280** [neherlab/covid19_scenarios#450]
# 🐛 Bug Report
When attempting to run application using 'yarn dev', I get the above error. Error points to 'import Ajv from 'ajv'' line in tools/convertSchemasToType.ts. If I comment that line out then it repeats the error with the next import, rimraf. Running 'yarn install' prior to 'yarn dev' does not solve issue. Possible that imports are not being handled correctly?

## How to reproduce

Steps to reproduce the issue:

 1. Run 'yarn dev'. Note errors in console.

## 😯 Current Behavior

`covid19_scenarios\tools\convertSchemasToType.ts:1
import Ajv from 'ajv'
       ^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at Object.<anonymous> (covid19_scenarios\node_modules\@babel\node\lib\_bab
el-node.js:180:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

## 🤔 Expected Behavior
Program should start up normally.

## 🌍 Your Environment
Using Windows 10, VSCode, Bash.

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System |
|                  |

## Related
Possibly related to #430 ?

**Comment by ivan-aksamentov** [comment]
@kmid5280 Windows?

**Comment by ivan-aksamentov** [comment]
This line:
https://github.com/neherlab/covid19_scenarios/blob/3b3ca469c2d1cf0b904ed7c3345cda84f4fa3e0c/package.json#L9

needs quotation marks, like here:
https://github.com/neherlab/covid19_scenarios/blob/3b3ca469c2d1cf0b904ed7c3345cda84f4fa3e0c/package.json#L17
Otherwise babel-node does not see the .ts files and does not transpile the script.

Could you please try and PR if it works?

**Comment by kmid5280** [comment]
@ivan-aksamentov That appears to have worked! I made a PR, but will let you know if I run into additional issues.

**Comment by ivan-aksamentov** [comment]
Should have been resolved in #452, theoreticallly.
If not, feel free to open an issue and/or PR.
