### ISSUE TITLE
Pasting shared URL does not restore the scenario name

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#459]
# 🐛 Bug Report

URL deserialization does not restore all of the data.
In particular, does not restore the scenario name.

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser
 2. Change a param. Click "Run"
 3. Copy the URL
 4. Open new tab, paste and go
 5. Observe scenario name is missing in the dropdown.
 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System |
|                  |

## Related

 -

**Comment by dkozar** [comment]
Actually it works for me (in staging). This is what I see in both the original and new tab:

![image](https://user-images.githubusercontent.com/1078403/78667207-6fa77e80-78d0-11ea-80ad-668f554883c6.png)

The scenario name is selected in the new tab.

However, I think the scenario selection was never meant to be persisted and should be removed. See https://github.com/neherlab/covid19_scenarios/issues/397.

**Comment by ivan-aksamentov** [comment]
Looks like that was the data issue which is now resolved
