### ISSUE TITLE
URL sharing on social media

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#462]
# 🙋 Feature Request

Introduce explicit sharing action through:
 - [x] email
 - [x] twitter
 - [ ] optionally other popular social media

## 💁 Possible Solution

It is desirable to use either an aggregator "alll-in-one" library, preferably React-aware, or the official SDKs per media outlet.

## Related

 -
 -

**Comment by kmid5280** [comment]
Do you mean react-share? Also where would you want the sharing icons to go? I see in the upper right corner there are already links to Twitter and Github.

**Comment by ivan-aksamentov** [comment]
@kmid5280 `react-share` looks okay, yes. I think we should put those in "Export, near where the sharing link copy is.

We might rename "Export" to something else later (not in this issue).

**Comment by kmid5280** [comment]
@ivan-aksamentov I tried playing with react-share a bit, but after installing using yarn add and importing, I got several module-related errors in the console when I tried to use it. Not sure if it's an issue on my end or with the plugin itself.

**Comment by ivan-aksamentov** [comment]
Resolved in #499
