### ISSUE TITLE
Fix truncation of locale dropdown

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#474]
# 🐛 Bug Report

Fix truncation of locale dropdown:

![Screenshot from 2020-04-08 14-14-15](https://user-images.githubusercontent.com/9403403/78783096-5c191800-79a3-11ea-88d6-e8f8f0a20c08.png)

***IMPORTANT*** Navbar items should be kept scrollable on mobile.

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser
 2.
 3.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System |
|                  |

## Related

 -

**Comment by guandiyiyi** [comment]
sent a PR for the fix

**Comment by ivan-aksamentov** [comment]
Resolved in #484
