### ISSUE TITLE
Link for raw Swiss Data is 404 

### ISSUE THREAD

**Issue by Hymenopteran** [neherlab/covid19_scenarios#487]
"https://raw.github.com/openZH/covid_19/master/COVID19_Cases_Cantons_CH_total.csv" goes nowhere. is this correct?

**Comment by noleti** [comment]
Thanks for pointing this out! I assume the URL was taken from the .tsv header, or the sources 'json'? These values are outdated, there are per canton paths now. Example: https://raw.githubusercontent.com/openZH/covid_19/master/fallzahlen_kanton_total_csv/COVID19_Fallzahlen_Kanton_ZH_total.csv

I will update the parser and sources to reflect this in the documentation
