### ISSUE TITLE
CAN-Quebec population data

### ISSUE THREAD

**Issue by wapebira** [neherlab/covid19_scenarios#491]
CAN-Quebec Population Data
Population: 8484965  
source: https://www.stat.gouv.qc.ca/statistiques/population-demographie/structure/qc_1971-20xx.htm
Hospital Beds: 7000 
source:https://www.cbc.ca/news/canada/montreal/numbers-covid-19-coronavirus-quebec-april-1-1.5518397
ICU Beds: 633
source:https://www.cbc.ca/news/canada/montreal/numbers-covid-19-coronavirus-quebec-april-1-1.5518397

**Comment by noleti** [comment]
Thanks! Not sure why we were missing Quebec.
