### ISSUE TITLE
Adding a legend "ICU beds"

### ISSUE THREAD

**Issue by WalkerWalker** [neherlab/covid19_scenarios#5]
Hopefully a legend "ICU beds" can be added.  I guess it's important to compare ICU beds with critical?

**Comment by rneher** [comment]
thanks. this should partially addressed in f4691f4550114217ccd168a5e8d318cda7af0a24.
numbers for switzerland might not representative though.
We'll look into adding numbers of other countries.

**Comment by WalkerWalker** [comment]
thanks!
