### ISSUE TITLE
Export all data

### ISSUE THREAD

**Issue by rneher** [neherlab/covid19_scenarios#504]
## 🙋 Feature Request
Currently our table export only includes the totals, not age specific numbers. Users have requested these for downstream reporting.

## 🔦 Context
give users access to more data

## 😯 Describe the feature
this could either be a much later table, or many tables (one for each age-group and the totals)

## 💁 Possible Solution
One could generalize the tsv export function. 

## Related
https://github.com/neherlab/covid19_scenarios/discussions/18#discussioncomment-4055

**Comment by nnoll** [comment]
I solved this somewhat by introducing another export button that outputs all stratified data to a tsv. I think this solves most things people would want. The only additional thing would be if people wanted to output subsets of ages but this seems rather esoteric to me.

**Comment by ccpf** [comment]
It would also be helpful if the export included the actual data as well, plus the mitigation periods, not just the model data. I.e., the export should include all the data necessary to recreate the figure.

**Comment by nnoll** [comment]
Hey @ccpf thanks for the feedback! The mitigation periods are included within the exported json. Furthermore, all data we use can be found on this repo here within the data/ folder.
