### ISSUE TITLE
Translation files other than English should not be automatically filled with english strings

### ISSUE THREAD

**Issue by whiver** [neherlab/covid19_scenarios#507]
### Context
Running `yarn i18n` extracts all the i18next strings from the code and merge them in the translation files.

### Issue
Commit 7acfbde2ae6bac5f250a2bc45d71dcfd474b973e changed the file `config/i18next/i18next.config.js` to automatically extract the i18next keys found in the code to every translation file, and not only the english one.

#### Why it is an issue
I believe this is not a good thing to populate other translation files, as we end up having the key, which is an english string, as translated value for each locale. This prevent from easily seeing which translations are missing for a locale and improve the risk to leave some english strings, as we then need to review the whole translation file to find the missing translations. And in any case, if a translation is missing in the translation file i18next will use the key instead, so the behaviour will be the same.

This also prevent localization platforms from correctly showing the translation completion for each locale, as the translation file appears to be complete, but actually isn't translated.

### Solution

The good way to handle new strings is usually to only add them in the english translation file, which then serves as a reference to translate to any other language. This is also how most translation platforms work: they compare each translation file to the reference one (usually English) to find missing translations and give the original sentence to translate.

**Comment by ivan-aksamentov** [comment]
@whiver I reverted the config and translations.
