### ISSUE TITLE
Backbone for adapt it to local needs

### ISSUE THREAD

**Issue by elrdrgz** [neherlab/covid19_scenarios#54]
Hi, 
Thanks for developing this tool! We are trying to develop a tool that helps local/regional mitigation efforts within a country (Bolivia). Using your scripts would be quite useful by saving us tons of time in developing the model. We would then include idiosyncratic conditions, such as local hospital coverage, new cases emerging, etc. We expect this to support targeted interventions in very low capabilities environments. However, I have not been able to spot the piece of the script that contains the pure contagion/recovery/death modeling part (the backbone of the tool). Would you please be so kind to refer me to where I can find it? Sincerely appreciate it. 
Thanks and best, 
Rodrigo

**Comment by nnoll** [comment]
The model can be found in src/algorithms/model.js. The function initializePopulation will return a data structure that the function evolve iterates on. The equations being simulated can also be found on the About page of the website

**Comment by elrdrgz** [comment]
Thanks. Much appreciated!!
