### ISSUE TITLE
Improve UI and UX around new uncertainty functionality

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#580]
# 🙋 Feature Request

With new parameter (and results) uncertainty functionality we now need to build a new user experience around this features.

## 🔦 Context

After #537 merged we now have a very important algorithmic improvement:

 - instead of specifying the exact value, users now can specify the range in which parameter is distributed (currently R0 and mitigation strengths)
 - the "Results" plots now show mean value (line) and the distribution where the result can fall with some probability (colored areas).
 - numeric representation now shows mean value and upper and lower bound
 - currently input parameters range is represented by a slider

## 😯 Describe the feature

Play with different representations and suggest the most suitable: 
 - [ ]  of parameter input for R0: maybe slider with 2 or 3 knobs, with or without editable numbers?
 - [ ]  of parameter input for mitigation strength: maybe slider with 2 or 3 knobs, with or without editable numbers?
 - [ ] representation of the output results on the plot (min, lower, upper)
 - [ ] representation of the output results in numeric form, such as in the plot tooltip
 - [ ] representation of the output results in the results table in the print preview page

## Related

 - #537 
 - #269

**Comment by gj262** [comment]
For parameter input I'd suggest switching to a freeform input that would allow single values and a range separated by 'to' or '-'. Ideally it would provide a hint that a range can be entered as the user types. A tooltip and placeholder could be used to explain the options.

![Typing hint](https://user-images.githubusercontent.com/6854428/79669614-920f8680-8171-11ea-9bdb-8ebeb76c8f6a.png)

![With a range](https://user-images.githubusercontent.com/6854428/79669615-963ba400-8171-11ea-97aa-b77420dcb9e3.png)

**Comment by ivan-aksamentov** [comment]
This was mostly resolved in #604 and #643
