### ISSUE TITLE
[1.2] A detailed run toggle

### ISSUE THREAD

**Issue by nnoll** [neherlab/covid19_scenarios#582]
# 🙋 Feature Request

With the addition of parameter uncertainty ranges, we now run a set of simulations and report on the statistics of trajectories that are output. Currently, to maintain interactivity with the user, we cap the number of samples to 10 as each simulation run takes ~50ms to run. 

We would like to provide the user a way to ask for a more detailed analysis/sampling of the chosen parameter ranges. The purposed UX is that the quick results would allow one to drill down to reasonable parameter estimates that one could simulate in detail with this feature.

## 🔦 Context

Currently the Run button is hard-coded to run 10 simulations and report the geometric mean and standard deviation. We would like to report percentiles but to do this accurately more runs are needed.

## 💁 Possible Solution

I see three potential solutions, each with pros and cons.

- [x] Have some kind concurrent process we could submit jobs to that run the detailed simulation in the background while displaying the fast results. The benefit of this is that running a detailed simulation requires minimal disruption to the overall exploration of scenarios. The cons is the potential complexity on the software engineering side.
- [ ] Have a "detailed run" button. When pressed a busy wheel comes up and the user has to wait for the results. Pros are that it's easy to implement. Cons are this would limit the detail one could simulate as it forces the user to wait with the simulation.
- [x] Allow the user to specify number of runs as a parameter. Pros are that its easy and minimal distortions to UI. Cons are this is a relatively technical parameter and will interact poorly with the autorun if the user tunes it to a large enough (> 20) number. I don't like this personally.

## Related

Issue #580, #581

**Comment by nnoll** [comment]
I envision this to act as a place of discussion (hence the talk tag) about what the best thing to do here in regards to UX.

**Comment by ivan-aksamentov** [comment]
#599 implemented a spinbox that sets number of runs and #610 caps the value at 10 minimum.
The maximum is 100. Default is 10.

Let's see how it goes and replace with a more sophisticated solution if needed.

Ideas are welcome.

**Comment by ivan-aksamentov** [comment]
This was mostly resolved in  #505  #599 #610
