### ISSUE TITLE
Modeling exposed individuals can also infect others with certain probability

### ISSUE THREAD

**Issue by WalkerWalker** [neherlab/covid19_scenarios#6]
Again thanks for the project.  Yet another suggestion and by no means it is a priority. I've read from various sources that the exposed individuals, who have no symptoms, can also infect others.  With what probability I don't know.  Maybe this can be another reasonable parameter.  

Thanks!

<img width="988" alt="Screen Shot 2020-03-12 at 1 51 03 PM" src="https://user-images.githubusercontent.com/8481463/76523543-e2a40d80-6468-11ea-8924-f8d0ac0416c3.png">

**Comment by rneher** [comment]
This is an interesting idea. We are effectively interpreting 'I' as infectious rather than symptomatic.

**Comment by WalkerWalker** [comment]
Thanks for the reply.  I think taking the fact "exposed individuals, who have no symptoms, can also infect others" into account is important.

**Comment by ivan-aksamentov** [comment]
Hi @WalkerWalker, I will close this issue for now, but let us know in #18 if you have more questions or suggestions!
