### ISSUE TITLE
IE11: Two crashes

### ISSUE THREAD

**Issue by gj262** [neherlab/covid19_scenarios#612]
# 🐛 Bug Report

run() crashes with "Worker Error" and "Promise is undefined".

Changing the scenario results in an error page. Something to do with immer.

## How to reproduce

IE11 and click Run
IE11 and select a scenario

![0003screenshot (1)](https://user-images.githubusercontent.com/6854428/79809605-c88e0280-8325-11ea-9e8d-06ec030af9c3.png)

![0003screenshot (1)](https://user-images.githubusercontent.com/6854428/79809664-f1ae9300-8325-11ea-81e4-03a4679175a7.png)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | IE11 |
| Operating System | Win 10 |
|                  |

## Related

 -

**Comment by ivan-aksamentov** [comment]
I tried to solve it in 7e56a2ea5b4131a5056bbd76098431aea83ac1ee. 

No idea why immer is involved at all, but I replaced its init to ES5 version. Also added polyfills to the worker, similar to how it's done for the entry point.

Worker still does not run occasionally, now silenty. Not sure what's going on.

**Comment by abrie** [comment]
Has 59f8c85d3 fixed the issue?

**Comment by gj262** [comment]
Yes, both issues are resolved in the latest master.
