### ISSUE TITLE
talking

### ISSUE THREAD

**Issue by DoctorWhoFR** [neherlab/covid19_scenarios#63]
Maybe working and adding on data of people who works now for country with lockdown to simulate virus propagation diminution and how many time needed to stop?

**Comment by ivan-aksamentov** [comment]
Hi @DoctorWhoFR , thanks for your suggestion!

We currently have a plot in the "Mitigation" scenario section. It allows you to simulate the mitigation (containment) measures, suck as self-isolation, over time. You can drag black dots to make mitigation

Another related parameter is R0, which defines how many persons a sick person will infect on average.

These are the high-level parameters, affecting the whole region, but we are also working on agent-based simulation, where we simulate on per-person basis. 

Let me know if you have further questions or suggestions!
