### ISSUE TITLE
Performance optimizations for tree and map visualizations

### ISSUE THREAD

**Issue by benlesh** [neherlab/covid19_scenarios#65]
I just spoke with @colinmegill about what could be done to improve the performance of the visualizations.

### Don't render any visualization that is not on the screen

There are a variety of ways to do this, `IntersectionObserver` is a solid tool for that, and it should be an easy win. It exists in every browser but IE. (I **highly** recommend ditching support for IE.. if we're talking about working on something that will help save lives, we shouldn't slow down progress for a browser that is dead in a year) If IE _must_ be supported, then we'd gate the functionality on the existence of `IntersectionObserver`.

### Render all "circles" in the tree view to Canvas overlay

- Use a transparent canvas to render, just the circles alone, they move on their own between views, there are a LOT of them, and Canvas can easily render these circles quickly and efficientely.
- For user interactions, you would use a transparent `<div>` overlay that intercepts all user interactions to check to see if the `mousemove` or `click`, etc events are "over" one of the circles. This can be done via simple and efficient coordinate lookup with a library called `RBush`.
- The brush overlay would be another layer, so as to prevent the re-rendering of the circles underneath during brushing, helping performance.

### Render all circles in the map view as a Leaflet canvas overlay

There are a number of examples around of how to do this. The first one I found was [here](http://bl.ocks.org/Sumbera/11114288). The same general idea as above. It might be that you want to do more than one overlay. one fo the circles, and one for the bezier arcs, so as you're brushing the number of updates required are minimal.

### Other thoughts

It's going to become important to abstract the location/positioning data away from any component they may currently be residing in now. This is so it can be reused effectively by newer code as you transition from SVG to Canvas. The upside is that the coordinate system between 2d canvas and SVG is basically the same, X,Y coords originating from the top left.

It's also worth mentioning that the calculations are _very unlikely_ to be the bottleneck to good performance here. So it's probably best not to waste too much effort on those. Computers are pretty fast at dealing with sets of numbers and calculations, even in JavaScript. At the moment that does become an issue we can address it.. move it to a worker, WASM, etc. But for now, the biggest choke point is the DOM rendering.

## Actions to be taken

- [ ] analyze the positioning algorithms used, and try to abstract them away from any rendering logic
- [ ] Attempt to implement a canvas layer for the tree circles
   - [ ] Render the circles to canvas
   - [ ] Create position indexing with RBush
   - [ ] Add transparent div to handle user events like hovers and clicks
   - [ ] Have transparent div handle scrolling and update the canvas rendering and position index (rbush)
- [ ] Attempt to implement the map overlays
  - [ ] Create a map overlay for pie charts
    - [ ] Create a drawing function for drawing a pie chart with Canvas context
    - [ ] Add the Leaflet canvas layer and render the pie charts
  - [ ] Create a map overlay for the "circles" for the connected circles visualization
  - [ ] Create a map overlay for the brush-animated arcs, and wire it up to update on brush selection
- [ ] Look into the easy win of not rendering visualizations that are off-screen.
  - [ ] Create a component that will render a different set of children if it is some specified percentage offscreen, something like: `<OffscreenChecker percent={80}>{(isOffscreen) => isOffscreen ? <div className="greyplaceholder"></div> : <ActualComponent/></OffscreenChecker>`... There may even be existing components that can do this.

**Comment by dhrubesh** [comment]
Hi @benlesh mind if I pick this up?

**Comment by dhrubesh** [comment]
@benlesh mind if I pick this up? It's 4am right now, will wake up tomorrow and discuss the approach in this thread.

**Comment by ivan-aksamentov** [comment]
Hi Ben @benlesh ,
I don't understand what it's all about. I need some more info! :)
Did you mean to submit it to nextstrain/auspice?

**Comment by benlesh** [comment]
Yes... sorry. Wrong repo. 🤦‍♂

**Comment by ivan-aksamentov** [comment]
@benlesh Haha, no worries! And thanks for stopping by :)
If you have time and forces -- contributions are always welcome!
