### ISSUE TITLE
Make footer prettier

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#660]
# 🙋 Feature Request

## 😯 Describe the feature

Footer at the bottom of the page is a bit ugly right now. We need to:
 - [ ] Adjust padding and margins
 - [ ] Align text on mobile and desktop
 - [ ] Possibly introduce more links and "powered by" logos

## Related

 -
 -

**Comment by snack-attack** [comment]
Hello, I'd like to contribute to this issue. I've actually already made the first two changes and will submit a PR in a moment. Do you know which links / logos you want added to the footer yet?

**Comment by ivan-aksamentov** [comment]
Hi @snack-attack , thanks!

We don't have a strict TODO here, so some imagination is required :)

I thought maybe add logos for Neherlab, Biozentrum and University of Basel, similar to the ones on print preview (in the app: export -> preview, src: components/Main/PrintPage)?

Vercel (aka Zeit aka now.sh) helped us a lot. So maybe add their "powerd by" logo?

Also maybe a link to GitHub page?

Would be nice to make the version text clickable, i.e. version number to link to the tagged commit, hash - to commit and build - to travis log?

We are also planning to add a citation to the paper, at least on desktop. Not sure if it fits stylistically. Here it is:
https://www.medrxiv.org/content/10.1101/2020.05.05.20091363v1
See "citation tools" for the text and the link should follow that. Does it make sense to make it an MDX component for easier text formatting?

I'd be glad if you'd explore the possibilities!
