### ISSUE TITLE
Prettify cards

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#662]
# 🙋 Feature Request

## 😯 Describe the feature

We could
 - [ ] change the background color of parameter cards to align with results card
 - [ ] remove borders
 - [ ] add box shadows
 - [ ] enable rounding in bootstrap's config
 - [ ] possibly change the "primary" color from green back to blue so that it is more distinct from "success" color (in bootstrap terms)

## Related

 -
 -

**Comment by yewyewXD** [comment]
Hi, @ivan-aksamentov ! I'm a new open source contributor, I'd love to help fix this issue. Which card are you referring to? How can I find the right file and make the changes on my local machine?

**Comment by ivan-aksamentov** [comment]
Hi @yewyewXD,

I think this issue is no longer relevant as we've had a redesign since then.

You see that the left and right sides of the app on this old screenshot from the readme have different colors:
https://user-images.githubusercontent.com/9403403/78839853-9c0aea00-79f9-11ea-92c9-593e05fd1570.gif
but it's no longer the case in the current app.
(we call those left and right sections "cards", because these are [Bootstrap's Card](https://reactstrap.github.io/components/card/) components)

I will close this, but feel free to look around for other issues that might pick your interest. There are still many visual and usability problems in the app, so if you notice something you can improve, don't hesitate to propose changes even if there's no issue open for it. Follow [Developer's Guide](https://github.com/neherlab/covid19_scenarios#%EF%B8%8F-developers-guide) to get started and if you encounter any difficulties, just ping me.

Thanks!
