### ISSUE TITLE
Redesign outcomes card

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#686]
# 🙋 Feature Request

## 🔦 Context

The outcomes card (on the right side of the screen towards the bottom) needs some more love

## 😯 Describe the feature

No fixed TODO list, a a creative approach is needed here, but here are some items to get started:

 - [ ] find a more visually appealing representation for the data (plot, table etc.)

 - [ ] align terminology between 2 sections
      - "mild", "severe", "critical", "fatal" vs "death", "severe", "severe", "critical".

 - [ ] potentially bring more data items there, for symmetry/completeness
     - Should totals and peaks be all pairs?
     - Should totals and peaks include all of the categories on the left?

## Related

 -
 -

**Comment by osnofas** [comment]
I would add a table with subtotals by age group. The information is now only available in a chart. Subtotals for {deaths, severe} × {underage (<18), working age (18-64) and retirement age (>=65)} would be extremely informative to the users.

**Comment by ivan-aksamentov** [comment]
@osnofas Sure, that sounds reasonable.

One thing to watch out is that it should be displayed equally well in the results section and in the print preview (they use the same component).

If you have time resources, feel free to try it.
