### ISSUE TITLE
Add progress indicator for the results section

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#688]
# 🙋 Feature Request

## 🔦 Context

Currently, when algorithm is running, the progress is only indicated on the "Run/Refresh" button. We need to add some sort of a progress indicator in the results section itself, to make it more intuitive.

## 😯 Describe the feature

 - [ ] should clearly show that the algorithm is running and that the results are about to change
 - [ ] should not obscure the plot completely, such that the moment when changes arrive can be seen
 - [ ] the indicator timing should be fully aligned with the indicator on the button

Various creative solutions should be tried (spinners, text, fade overlay etc.) until good UX is achieved.

## Related

 -
 -

**Comment by Chong-anson** [comment]
Hi, I am trying to make my first commit to an open source project and I would love to claim this issue!

**Comment by ivan-aksamentov** [comment]
@Chong-anson sure, give it a try. Thanks!

**Comment by Chong-anson** [comment]
I suppose we need to add loading progress to cover the plot?

**Comment by Chong-anson** [comment]
Hi Ivan, my idea is to create a component similar to RunButtonContent, which will display a loading spinner when the plot is loading. I'm also thinking adding a props to the ResultCard to "blur out" the plot when it is loading. What do you think about this?

**Comment by ivan-aksamentov** [comment]
Resolved in #706
