### ISSUE TITLE
Death rates should increase when ICU's are overwhelmed

### ISSUE THREAD

**Issue by patrickturko** [neherlab/covid19_scenarios#7]
For simplicity all age classes could be randomly assigned to an ICU bed. When bed space is exceeded, the fatality rate of remaining severe / critical cases should increase. 

The number of ICU beds should also be editable. In Switzerland we have [1000 beds, total](https://www.luzernerzeitung.ch/news-service/inland-schweiz/intensivstationen-wappnen-sich-fuer-das-schlimmste-szenario-ld.1203245), not 40,000.

**Comment by rneher** [comment]
I added 1000 ICU + 400 ICM beds to the graph.

**Comment by aeon-lakes** [comment]
Randomising all ages doesn't appropriately model physician behaviour. In a disaster that exceeds capacity we go full-on utilitarian and assign for maximum benefit. The young and previously fit are prioritised as they are most likely to survive with treatment; take the least time to recover; and have the most lifespan to lose if untreated. 

In the situation where Critical Care is overwhelmed the deaths will fall on the over 70 age group.

**Comment by ivan-aksamentov** [comment]
Hi @patrickturko @aeon-lakes ,

We are thinking about adding some more realism to the algorithm, and I like both of these suggestions very much.

Please keep the ideas coming! :bulb:

**Comment by nnoll** [comment]
I've started a new branch feat/hospital-bed-model that starts to address this. Right now we model this by a non-linear function that models an increase in death rate as a function of total ICU capacity. Some more work on its realism is probably needed.

**Comment by aeon-lakes** [comment]
I think it needs two values for ICU. Total ICU beds and Ventilated Beds. 

All Critically Ill should be assigned an ICU bed. Around half of those (I don't have decent numbers, anyone?) should be made 'require ventilation'. If 'require ventilation' > ventilated beds then the excess should be assigned to Deaths. Once assigned a ventilated bed, survivors from that cohort should occupy the bed for 14 days and make it unavailable. Deaths for a random shorter period.

The remaining Critically Ill should be assigned to the remaining ICU beds. The excess will have a higher death rate than the ones treated. (Numbers?). Th ones just assigned to ICU but not ventilated will need a shorter stay.

The ability to scale up ventilated beds during the simulation run would also be helpful. I know European manufacturers are gearing up for much more production and my hospital has scavenged a couple more with hopefully more to follow, so it would be helpful to see how that affects deaths.

**Comment by rneher** [comment]
We implemented a first version of this escalation of fatality. If the number critically ill people exceeds the available ICU beds, the rate at which people in need of ICU but without access to ICU die is increased. this was merged in 77ab0db5d2887d6bf8dd2c82841609f9868d0c25
