### ISSUE TITLE
Improve mobile user experience

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#71]
Our current mobile experience is suboptimal. 

### Key defects:
 - Situation is particularly bad with charts and plots, which is a central aspect of the application.
 - Some of the elements are needlessly large, some are to small
 - Scrolling is awkward
 - Tapping "Run" button gives no clue that there is more content appeared below
 - Calendar is cut-off

We currently use reactstrap as a frontend library with some Sass stylesheets and bootstrap utility classes sprinkled here and there. As a team of 3 people, we would not able to change that. But if we find knowledgeable contributor(s) in UI/UX space, then the transition to another styling solution will become more realistic, including the full revamp of the UI.

Our main focus is desktop, with 720p or 1080p screen at least, but having broken mobile experience hurts the outreach, because we mostly promote our project on social media (Twitter). People are coming from there on the phones first, and they are probably not very impressed and are less compelled to switch or return with a larger device.

### Related issues:

 - Improve desktop user experience: https://github.com/neherlab/covid19_scenarios/issues/13

Screencast of "iPhone X" simulation in Chrome:

![mobile](https://user-images.githubusercontent.com/9403403/77221789-3986a280-6b4d-11ea-99fd-2d3b1eef4ec9.gif)

**Comment by ivan-aksamentov** [comment]
This is a huge issue. Feel free to open separate issues for smaller fixes and mention this one.

**Comment by miksa1987** [comment]
Hi! I could start working on the elements. As for clicking run and more items appearing, could it be done so that form items would be kind of like menu overlay on top of everything, and when clicking run, they go away to a menu button ready to be invoked again? 
Also, I was thinking about the popups in graphs, perhaps they should be placed on top of the graph on mobile, so that it wouldn't be on top of the pointer making it hard to tap on certain spot?

**Comment by ivan-aksamentov** [comment]
Hi @miksa1987,

> I could start working on the elements
It'd be awesome! Make sure you coordinate with other folks, such as in #83  and other issues and PRs listed above

> form items would be kind of like menu overlay on top of everything, and when clicking run, they go away to a menu button ready to be invoked again
That's a great design idea! 

> about the popups in graphs, perhaps they should be placed on top of the graph on mobile
That'd be fantastic! Although, I am not sure if our graph library allows that to be done easily or even at all. But I'd be glad if you can look into it!


Please, in order to ensure that the merge conflicts are small and there is no work wasted on different people doing the same thing, keep your work constantly visible:
 -  commit and submit or update PRs often
  - optionally mark PRs as "draft"
  - optionally create an empty "WIP" or "DO NOT MERGE" PR and keep pushing new commits into it
 -  discuss and coordinate in our Spectrum chat (in dev channel)

**Comment by miksa1987** [comment]
> > form items would be kind of like menu overlay on top of everything, and when clicking run, they go away to a menu button ready to be invoked again
> 
> That's a great design idea!

> > about the popups in graphs, perhaps they should be placed on top of the graph on mobile
> 
> That'd be fantastic! Although, I am not sure if our graph library allows that to be done easily or even at all. But I'd be glad if you can look into it!

I'm going to look deeper into these two today for starters and open an issue when I'm ready to start working. I really hope your graph library makes it easy(or even possible, like you said) to adjust the popup position based on, for example, media queries. Personally that was a major annoyance when I tried this on my phone.

I'll do this by starting a "DO NOT MERGE" PR first and when it's ready, I'll change the title?
I will join the chat too.

**Comment by ivan-aksamentov** [comment]
@miksa1987  Sounds like a plan!

> I'll do this by starting a "DO NOT MERGE" PR first and when it's ready, I'll change the title?
I will join the chat too.

Yes, you can remove the "WIP" or "DO NOT MERGE" status or draft flag and and I'll review and merge. You may also ping me with `@ivan-aksamentov` to make sure I pay attention :)
And of course, let me know if you need something.

**Comment by ivan-aksamentov** [comment]
There's been numerous PRs and mobile experience is somewhat better now.
We will address the remaining concerns in more focused issues.
