### ISSUE TITLE
[Bug] Effect of "Infectious Period"

### ISSUE THREAD

**Issue by SKloeser** [neherlab/covid19_scenarios#74]
Increasing the Infectious Period results in a less severe scenario and vice versa. I assume this is a bug.

**Comment by noleti** [comment]
Without any background in the topic, I assume that R0 is per case (not time and case), so increasing infectious period to 10 days will mean that the 2.7 infections per case are spread over 10 days now, instead of 3. This will then reduce the speed of propagation.

**Comment by SKloeser** [comment]
If this is the case the description should be adjusted.

**Comment by rneher** [comment]
Yes. @noleti is correct. this might be unintuitive, but is the correct behavior.
