### ISSUE TITLE
[Bug] Fix overlapping of y-axis text on mitigation chart

### ISSUE THREAD

**Issue by keevcodes** [neherlab/covid19_scenarios#78]
Browser (include version): Chrome 80
Operative System: Mac OS Catalina

## The current behavior

On mobile, the y-axis text on the mitigation chart overlaps to the point where the chart is unreadable. 

Iphone X Chrome: 

<img width="639" alt="Screenshot 2020-03-21 at 12 56 01" src="https://user-images.githubusercontent.com/17259420/77225847-69e13780-6b73-11ea-83e4-913cb4793d95.png">

## The expected behavior

Text should be displayed to the user clearly 

related:

#71

**Comment by keevcodes** [comment]
I'd like to tackle this issue

**Comment by keevcodes** [comment]
@ivan-aksamentov  I think I've got a solution for this issue, however when trying to push to the newly created branch 'issue/78' I get a `remote: Permission to neherlab/covid19_scenarios.git denied to keevcodes.`

**Comment by petebacondarwin** [comment]
@keevcodes did you fork the repository to your own account?

**Comment by petebacondarwin** [comment]
For example I have https://github.com/petebacondarwin/covid19_scenarios
And I would add this to my local github as a remote via:

```
git remote add pete https://github.com/petebacondarwin/covid19_scenarios 
```

Then instead of trying to push to the source repository you push to your own fork:

```
git push -u pete my-local-branch-name
```

(Hopefully this is not teaching you to suck eggs :-) )

**Comment by keevcodes** [comment]
@petebacondarwin  I completly overlooked that fact.. truth be told I know better, chalking this up to a typical dev brain fart moment. Thanks for the reminder

**Comment by nnoll** [comment]
@petebacondarwin beat me to it. Please fork the repo and submit a pull request with your fix. Thanks for your help!
