### ISSUE TITLE
Results unexpectedly depend on time span

### ISSUE THREAD

**Issue by robjohnnoble** [neherlab/covid19_scenarios#8]
A UZH colleague of mine, Barbora Trubenova, has spotted that the model results depend on the chosen time window. For example, with default parameter values, the default time span until 12th September 2020 predicts 484 cumulative deaths by 1st August 2020. Changing the time span to 15th May 2021 changes the prediction to 920 deaths by 1st August 2020. The same applies to all other predicted values (see screenshots below). For an intermediate date, the predictions are intermediate. Therefore, at best, the model can be valid only for one particular time span.

<img width="656" alt="Screenshot 2020-03-12 at 22 39 53" src="https://user-images.githubusercontent.com/6522653/76570024-b7dfa680-64b4-11ea-871b-322c550d8ec7.png">
<img width="661" alt="Screenshot 2020-03-12 at 22 40 25" src="https://user-images.githubusercontent.com/6522653/76570027-b910d380-64b4-11ea-9320-c3cf474c3253.png">

**Comment by robjohnnoble** [comment]
Klaus Peper has explained on twitter that ,"Changing time span automatically changes dates of interventions which has massive effect. Not a bug in a narrower sense but an effect that easily could be overseen." I can see why you might decide to do this but it's not the behaviour I expected. Three of us (all mathematical biologists) concluded this was a bug. Perhaps at least a note could be added to explain this feature.

**Comment by rneher** [comment]
Thanks Rob. I agree its unexpected. We noticed this yesterday and added a note to alert users to this. We'll try to change this today.

**Comment by robjohnnoble** [comment]
One option would be to integrate the tools for setting timespan and mitigation schedule by modifying the interactive plot with the moveable black dots. First, fix the time range of this plot to the maximum permitted values (e.g. 1st March 2020 to 1st March 2021). Second, add sliders for setting the start and end dates of the model output. A bonus is that then you no longer need a separate calendar webpage.

**Comment by rneher** [comment]
this merge b553df91a408415040e26ee46752543f6659ca71 should fix this. We now resample the linear interpolation of the previous mitigation curve. that still might result in small differences due to interpolation errors. But should be a lot closer to what you expect. 

Thanks again for bringing it up. This was definitely unexpected behavior and needed fixing.
