### ISSUE TITLE
Missing (And wrong) data shown before 08-16-2020 

### ISSUE THREAD

**Issue by tiagoandresvaz** [neherlab/covid19_scenarios#862]
![error](https://user-images.githubusercontent.com/752397/110031450-b0dd2400-7d15-11eb-8cc7-3d5587b74442.png)

When selecting any start date before 08-16-2020 in simulation range, triggers a shift left in all data, showing all case counts one day before. For example, Lombardia today has data until 03-march (Patients in ICU data = 0.51k), and it shows ok when you load the scenario. But if you change simulation time range to start any date prior 08-16-2020 it will display the same 0.51k data but as 02-march and for day 03-march it will be empty.

Also, thick lines (data) are not show prior 08-16-2020, maybe it is related to the source of this error.

**Comment by rneher** [comment]
Hi Tiago,

I restricted the case-count export to the last 200 days, assuming that most people study recent dynamics. A better fix for that would be of course to allow more flexible zooming of the chart. But we currently don't have the capacity to implement this. 

but if this an issue for you, I can export the full data along side partial data or use the simulation time range to set the zoom level. 

best,
richard

**Comment by tiagoandresvaz** [comment]
Thanks Prof. Neher,
after your answer, this is not going to be a problem for us and I will close this issue.
regards, Tiago

**Comment by tiagoandresvaz** [comment]
added little info to release notes informing about 200 days limits in case-count export.
